import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import ts from 'typescript'
const code=ts.transpileModule(readFileSync(new URL('../../lib/notifications/common-contract.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText
const module={exports:{}};new Function('exports','module',code)(module.exports,module)
const {parseReadRequest,parseNotificationPage,mergeNotificationPages,newArrival,notificationCursor,resolveSocialLink,mentoringTargetMatches,mentoringInvitationOnly}=module.exports
const id='12345678-1234-4234-8234-123456789012'
const row=(n,read_at=null)=>({id:id.slice(0,-2)+String(n).padStart(2,'0'),kind:'social_activity',payload:{},created_at:`2026-09-10T12:00:${String(n).padStart(2,'0')}.000Z`,read_at})
test('a party X invitation while active in Y isolates the invitation view',()=>{const other=row(9).id,snapshot={party_id:other,session_id:other,phase:'active',invitations:[{party_id:id}]};assert.equal(mentoringTargetMatches(snapshot,{party:id}),true);assert.equal(mentoringInvitationOnly(snapshot,id),true);assert.equal(mentoringInvitationOnly(snapshot,other),false);assert.equal(mentoringInvitationOnly(snapshot,null),false)})
test('reading is explicit: malformed, ambiguous and empty input never means all',()=>{for(const body of [null,[],{},'',{all:false},{notification_id:'nope'},{notification_id:id,all:true},{all:true,extra:1}])assert.equal(parseReadRequest(body),null);assert.deepEqual(parseReadRequest({all:true}),{all:true});assert.deepEqual(parseReadRequest({notification_id:id}),{notification_id:id})})
test('list parsing fails closed and does not turn invalid response into empty inbox',()=>{assert.equal(parseNotificationPage({}),null);assert.equal(parseNotificationPage({notifications:[{id:'bad'}]}),null);assert.deepEqual(parseNotificationPage({notifications:[row(1)]}),[row(1)])})
test('refresh overwrites read state, preserves older page and deduplicates',()=>{assert.deepEqual(mergeNotificationPages([row(2),row(1)],[row(3),row(2,'2026-09-10T13:00:00Z')]).map(r=>[r.id.slice(-2),!!r.read_at]),[['03',false],['02',true],['01',false]])})
test('initial load and read/old backfill are not arrivals',()=>{assert.equal(newArrival(null,[row(3)]),null);assert.equal(newArrival([row(3)],[row(3),row(2)]),null);assert.equal(newArrival([row(3)],[row(4,'2026-09-10T13:00:00Z'),row(3)]),null);assert.equal(newArrival([row(3)],[row(4),row(3)]).id,row(4).id)})
test('cursor is based on date and id, with tied timestamp stable order',()=>{assert.deepEqual(notificationCursor([row(2),row(1)]),{before_created_at:row(1).created_at,before_id:row(1).id});assert.equal(notificationCursor([]),null)})
test('social resolver allows only known internal targets; terminal never redirects',()=>{for(const href of ['https://evil.test','//evil.test','/admin','/meetups/../admin','/meetups/%2e%2e/admin','/meetups/league?next=https://evil.test','/meetups/league#x'])assert.equal(resolveSocialLink({href,status:'current'}),null);assert.equal(resolveSocialLink({href:'/meetups/league?sport=lol&panel=applications',status:'current'}),'/meetups/league?sport=lol&panel=applications');assert.equal(resolveSocialLink({href:'/meetups/league',status:'ended'}),null)})
test('mentoring notification cannot silently open another session/party',()=>{const snapshot={session_id:id,party_id:id,invitations:[]};assert.equal(mentoringTargetMatches(snapshot,{session:id}),true);assert.equal(mentoringTargetMatches(snapshot,{session:row(2).id}),false);assert.equal(mentoringTargetMatches({...snapshot,invitations:[{party_id:row(2).id}]},{party:row(2).id}),true);assert.equal(mentoringTargetMatches(snapshot,{}),true)})
