'use client'
import {useCallback,useEffect,useState} from 'react'
import {useQuantumLocale} from '@/components/i18n/QuantumLocaleProvider'
import styles from './department-league.module.css'
type Review={id:string;challenge_id:string;reason:string;status:string;created_at:string;target_alias:string;position:string;self_reported_tier:string;restriction_id:string|null;ends_at:string|null;revoked:boolean;appeal_text:string|null;appeal_status:string|null}
export default function DepartmentLeagueModeration(){
 const{t}=useQuantumLocale();const[reports,setReports]=useState<Review[]|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch('/api/admin/super-admin/department-league',{cache:'no-store'});const p=await r.json();if(!r.ok||!Array.isArray(p?.review)||p.review.length>100||p.review.some((v:Review)=>!v||typeof v.id!=='string'||typeof v.reason!=='string'||typeof v.target_alias!=='string'))throw new Error();setReports(p.review)}catch{setReports(null);setNotice('challenge.loadError')}finally{setBusy(false)}},[])
 useEffect(()=>{void load()},[load])
 async function act(action:string,args:Record<string,unknown>){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/super-admin/department-league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,args})});if(!r.ok)throw new Error();setNotice('challenge.saved');await load()}catch{setNotice('challenge.failed')}finally{setBusy(false)}}
 return <main className={styles.review}><h1>{t('challenge.moderationTitle')}</h1><p className={styles.note}>{t('challenge.moderationNote')}</p><button type="button" disabled={busy} onClick={()=>void load()} className={styles.secondary}>{t('challenge.retry')}</button>{notice?<p role="status" className={styles.notice}>{t(notice)}</p>:null}{reports?.length?reports.map(report=><ReviewCard key={report.id} report={report} busy={busy} act={act}/>):reports?<p>{t('challenge.noReports')}</p>:null}</main>
}
function ReviewCard({report,busy,act}:{report:Review;busy:boolean;act:(action:string,args:Record<string,unknown>)=>Promise<void>}){
 const{t,locale}=useQuantumLocale();const[note,setNote]=useState('');const send=(action:string,days?:number)=>{void act(action,{report_id:report.id,note,...(days?{days}:{})})}
 return <article><p>{new Date(report.created_at).toLocaleString(locale)}</p><h2><strong>{report.target_alias} · {t(`challenge.${report.position}`)}</strong></h2><p className={styles.note}>{t('challenge.notVerified')} {t(`challenge.${report.self_reported_tier}`)}</p><p>{report.reason}</p>{report.appeal_text?<blockquote>{report.appeal_text}</blockquote>:null}<textarea aria-label={t('challenge.reviewNote')} placeholder={t('challenge.reviewNote')} value={note} minLength={10} maxLength={1000} onChange={e=>setNote(e.target.value)}/><div className={styles.reviewActions}>{report.status==='pending'?<>{(['dismiss','restrict14','restrict21'] as const).map(action=><button key={action} type="button" disabled={busy||note.trim().length<10} className={styles.secondary} onClick={()=>send(action==='dismiss'?'dismiss':'restrict',action==='restrict14'?14:action==='restrict21'?21:undefined)}>{t(`challenge.${action}`)}</button>)}</>:report.restriction_id&&!report.revoked?<><button type="button" disabled={busy||note.trim().length<10} className={styles.secondary} onClick={()=>send('restore')}>{t('challenge.restore')}</button>{report.appeal_status==='pending'?<button type="button" disabled={busy||note.trim().length<10} className={styles.secondary} onClick={()=>send('appeal_review')}>{t('challenge.keepRestriction')}</button>:null}</>:<p>{t(report.revoked?'challenge.restored':'challenge.reviewed')}</p>}</div></article>
}
