'use client'

import Image from 'next/image'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react'
import {useQuantumLocale} from '@/components/i18n/QuantumLocaleProvider'
import {PNU_DEPARTMENTS} from '@/lib/pnu-departments'
import {LEAGUE_SPORTS,buildLeagueRows,parseJourneyState,selectJourneyChallenge,sportTiers,leagueTeamName,type LeagueSport,type JourneyState,type JourneyTeam,type JourneyPlayer,type JourneyScheduleProposal} from '@/lib/meetups/challenge-journey'
import {makeLeagueDemo,advanceLeagueDemo,type LeagueDemoAction,type LeagueRankingExample} from '@/lib/meetups/challenge-journey-demo'
import {makeLeagueInviteDemo,advanceLeagueInviteDemo,leagueInviteDemoSnapshot,type LeagueInviteDemoAction} from '@/lib/meetups/league-invites-demo'
import type {LeaguePositionInvite} from '@/lib/meetups/league-invites'
import {useLeaguePositionInvites,LeagueInviteBell,LeagueInviteInbox,LeaguePositionInviteSheet,LeagueInviteReceiver} from './LeaguePositionInvites'
import LeagueHonors from './LeagueHonors'
import LeagueLobby,{leagueTeamSum} from './LeagueLobby'
import LeagueMatchChat from './LeagueMatchChat'
import LeagueTeamChat,{createLeagueTeamChatDemoTransport,type LeagueTeamChatDemoStore} from './LeagueTeamChat'
import {SocialChatDirectory} from '@/components/chat/SocialChatDirectory'
import LeagueRecruitment,{type LeagueRecruitmentBrowseState,LeagueRecruitmentNoticeForm,readLeagueRecruitmentDetail,leagueRecruitmentCommand,recruitmentError,isRecruitmentNoticeClosed} from './LeagueRecruitment'
import {makeLeagueRecruitmentDemo,emptyRecruitmentDemo,recruitmentDemoDetail,advanceRecruitmentDemo,type LeagueRecruitmentDemoAction} from '@/lib/meetups/league-recruitment-demo'
import type {LeagueRecruitmentDetail} from '@/lib/meetups/league-recruitment'
import {ArrowLeft, Medal, Plus, Shirt} from 'lucide-react'
import {LeagueTierBadge,LeagueTierPicker} from './LeagueTier'
import {LeagueApplicationIntro,LeagueApplicationSummary,type ApplicationIntro} from './LeagueApplicationIntro'
import {LeagueRecruitmentStatus,LeagueRequestReview,leagueRecruitmentCounts,leagueSlotState,leagueReviewNextStep,focusLeagueRecruitmentStatus} from './LeagueRecruitmentStatus'
import styles from './department-league-journey.module.css'

type Stage='sport'|'league'|'roster'|'opponents'|'match'|'result'|'report'|'invite'|'recruitment'|'publish'|'team-chat'|'team-chat-list'|'team-map'
type Target={id:string;alias:string;position:string;slot:string|null}
const endpoint='/api/community/department/league/journey'
async function readResponse(response:Response,key:string):Promise<unknown>{const payload=await response.json().catch(()=>null);if(!response.ok||!payload||!(key in payload))throw new Error(typeof payload?.error==='string'?payload.error:'invalid_response');return payload[key]}
function dateInput(hours:number){const date=new Date(Date.now()+hours*3600000);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}

export function DepartmentLeagueJourney({demo=false,initialSport,demoRanking='empty',demoFlow='league',initialInviteId,initialChallengeId,initialTeamId,initialReview=false,initialReviewSlot,coordinationOnly=false,initialResult=false,onDemoChatViewChange}:{demo?:boolean;initialSport?:LeagueSport;demoRanking?:LeagueRankingExample;demoFlow?:'league'|'invites'|'recruitment';initialInviteId?:string;initialChallengeId?:string;initialTeamId?:string;initialReview?:boolean;initialReviewSlot?:string;coordinationOnly?:boolean;initialResult?:boolean;onDemoChatViewChange?:(active:boolean)=>void}){
 const{t,locale}=useQuantumLocale()
 const router=useRouter()
 const [recruitmentViews,setRecruitmentViews]=useState<Partial<Record<LeagueSport,LeagueRecruitmentBrowseState>>>({})
 const[teamChatId,setTeamChatId]=useState<string|null>(null),teamChatStore=useRef<LeagueTeamChatDemoStore>(new Map())
 const[sport,setSport]=useState<LeagueSport|null>(initialSport??null),[stage,setStage]=useState<Stage>(initialResult?'result':initialInviteId?'invite':initialChallengeId?'roster':demo&&demoFlow==='invites'?'roster':demo&&demoFlow==='recruitment'?'recruitment':initialSport?'league':'sport')
 useEffect(()=>{if(demo){const chatView=stage==='team-chat'||stage==='team-chat-list'||stage==='match';onDemoChatViewChange?.(chatView);if(chatView)window.scrollTo({top:0,behavior:'instant'})}return()=>{if(demo)onDemoChatViewChange?.(false)}},[demo,stage,onDemoChatViewChange])
 const[data,setData]=useState<JourneyState|null>(null),[connection,setConnection]=useState<'loading'|'ready'|'error'>('loading'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const[selectedId,setSelectedId]=useState<string|null>(initialChallengeId??null),[draft,setDraft]=useState(demo&&demoFlow==='invites'),[selectedSlot,setSelectedSlot]=useState(''),[tier,setTier]=useState(''),[title,setTitle]=useState('')
 const[inviteDemo,setInviteDemo]=useState(makeLeagueInviteDemo),[inviteSlot,setInviteSlot]=useState<string|null>(null),[inviteId,setInviteId]=useState<string|null>(initialInviteId??null),[inviteChallengeId,setInviteChallengeId]=useState<string|null>(initialChallengeId??null)
 const[recruitmentDemo,setRecruitmentDemo]=useState(emptyRecruitmentDemo),[liveDetail,setLiveDetail]=useState<LeagueRecruitmentDetail|null>(null),[fromNotice,setFromNotice]=useState(false)
 const[applicationIntro,setApplicationIntro]=useState<ApplicationIntro>({aspiration:'',strengths:''})
 const[noticeTick,setNoticeTick]=useState(0),slotMutation=useRef(false)
 const[reviewOpen,setReviewOpen]=useState(initialReview),[reviewSlot,setReviewSlot]=useState<string|null>(initialReviewSlot??null),reviewPanel=useRef<HTMLDivElement>(null),operationMutation=useRef(false)
 const[reviewDecision,setReviewDecision]=useState<{challengeId:string;teamId:string;playerId:string}|null>(null),[statusReturn,setStatusReturn]=useState<{challengeId:string;teamId:string}|null>(null),rosterStatus=useRef<HTMLElement>(null)
 const activeDetail=useRef<string|null>(initialInviteId?null:initialChallengeId??null),detailGeneration=useRef(0)
 const stageStart=useRef<HTMLElement>(null)
 const[monthly,setMonthly]=useState(false),[search,setSearch]=useState(''),[gap,setGap]=useState<200|300>(200)
 const[startsAt,setStartsAt]=useState(()=>dateInput(2)),[endsAt,setEndsAt]=useState(()=>dateInput(3)),[place,setPlace]=useState(''),[scheduleSubmitted,setScheduleSubmitted]=useState(false),[ownScore,setOwnScore]=useState(2),[opponentScore,setOpponentScore]=useState(1)
 const[scheduleSnapshot,setScheduleSnapshot]=useState<{startsAt:string;endsAt:string;place:string}|null>(null)
 const[targets,setTargets]=useState<Target[]|null>(null),[targetError,setTargetError]=useState(false),[selectedTarget,setSelectedTarget]=useState(''),[reason,setReason]=useState(''),[reportSent,setReportSent]=useState(false)
 const definition=sport?LEAGUE_SPORTS[sport]:null
 const selected=selectJourneyChallenge(data,selectedId,draft)
 useEffect(()=>{setReviewOpen(initialReview&&selected?.id===initialChallengeId);setReviewSlot(initialReviewSlot??null)},[selected?.id,initialReview,initialChallengeId,initialReviewSlot])
 const exactTeam=!!initialTeamId&&selected?.id===initialChallengeId
 const team=exactTeam?selected?.teams.find(team=>team.id===initialTeamId)??null:selected?.teams.find(team=>team.is_mine)??selected?.teams.find(team=>team.department===data?.my_department)??null
 const captainPreview=demo&&recruitmentDemo.captainChallengeId===selected?.id
 const me=captainPreview?undefined:team?.players.find(player=>demo&&inviteDemo.viewer==='recipient'?player.id===inviteDemo.recipientId:player.is_me),locked=!!selected&&selected.status!=='recruiting'
 const isTeamMember=!!team&&!!me&&me.status==='accepted'
 const chatChallenge=data?.challenges.find(challenge=>challenge.teams.some(candidate=>candidate.id===teamChatId)),chatTeam=chatChallenge?.teams.find(candidate=>candidate.id===teamChatId)
 const chatViewer=chatTeam?.players.find(player=>demo&&inviteDemo.viewer==='recipient'?player.id===inviteDemo.recipientId:player.is_me)
 const chatAllowed=chatViewer?.status==='accepted',chatOwner=chatViewer?.id??inviteDemo.recipientId??'93000000-0000-4000-8000-000000000999'
 const demoChatTransport=useMemo(()=>demo&&sport&&chatTeam&&chatChallenge?createLeagueTeamChatDemoTransport(teamChatStore.current,chatOwner,{team_id:chatTeam.id,challenge_id:chatChallenge.id,title:leagueTeamName(chatTeam,chatChallenge.title),department:chatTeam.department,sport,member_count:chatTeam.players.filter(player=>player.status==='accepted').length,writable:true},chatViewer?.alias??'팀원',chatAllowed):null,[demo,sport,chatTeam,chatChallenge,chatOwner,chatViewer?.alias,chatAllowed])
 useEffect(()=>{if(reviewOpen&&stage==='roster'&&team?.is_captain&&!locked){reviewPanel.current?.scrollIntoView({block:'start'});reviewPanel.current?.focus({preventScroll:true})}else if(['recruitment','publish','roster'].includes(stage))stageStart.current?.scrollIntoView({block:'start'})},[stage,selected?.id,reviewOpen,reviewSlot,team?.is_captain,locked])
 useEffect(()=>{setApplicationIntro({aspiration:'',strengths:''})},[sport,selected?.id,me?.id])
 const reservations=inviteDemo.records.filter(invite=>invite.status==='pending'&&Date.parse(invite.expires_at)>Date.now()).map(invite=>({team_id:invite.team_id,slot:invite.slot}))
 const detail=demo&&data&&selected&&['roster','publish'].includes(stage)?recruitmentDemoDetail(data,recruitmentDemo,selected.id,reservations):liveDetail?.challenge.id===selected?.id?liveDetail:null
 const noticeClosed=fromNotice&&isRecruitmentNoticeClosed(detail?.notice),noticeDeadline=fromNotice?detail?.notice?.expires_at:null
 useEffect(()=>setGap(team?.gap??200),[team?.id,team?.gap])
 const rows=data?buildLeagueRows(PNU_DEPARTMENTS,monthly?data.monthly_standings:data.standings,data.my_department,monthly):[]
 const visibleRows=rows.filter(row=>!search||row.department.includes(search)).slice(0,search?300:12)

 const load=useCallback(async(signal?:AbortSignal,quiet=false)=>{
  if(!sport)return null
  if(demo){setConnection('ready');return null}
  if(!quiet)setConnection('loading')
  const version=++detailGeneration.current,targetId=activeDetail.current
  try{const parsed=parseJourneyState(await readResponse(await fetch(`${endpoint}?sport=${sport}`,{cache:'no-store',signal}),'journey'));if(!parsed||parsed.sport!==sport)throw new Error('invalid_journey');const current=targetId?await readLeagueRecruitmentDetail(sport,targetId,signal):null;if(!signal?.aborted&&version===detailGeneration.current){setLiveDetail(current);setData(current?{...parsed,challenges:[current.challenge,...parsed.challenges.filter(challenge=>challenge.id!==current.challenge.id)]}:parsed);setConnection('ready')}return parsed}
  catch{if(!signal?.aborted&&version===detailGeneration.current){setData(null);setLiveDetail(null);setConnection('error')}return null}
 },[sport,demo])
 const refresh=useCallback(()=>load(undefined,true),[load])
 useEffect(()=>{if(!noticeDeadline)return;const remaining=Date.parse(noticeDeadline)-Date.now();if(!Number.isFinite(remaining)||remaining<=0)return;const timer=window.setTimeout(()=>{setNoticeTick(value=>value+1);if(!demo)void refresh()},Math.min(remaining+25,2147483647));return()=>window.clearTimeout(timer)},[noticeDeadline,noticeTick,demo,refresh])
 const inviteContextId=stage==='invite'?inviteChallengeId:stage==='roster'&&team?.players.some(player=>player.is_me&&player.status==='accepted')?selected?.id??null:null
 function simulateInvite(action:LeagueInviteDemoAction){if(!demo||!data)return;const next=advanceLeagueInviteDemo(data,inviteDemo,action);setData(next.journey);setInviteDemo(next.invites)}
 const invites=useLeaguePositionInvites({sport,challengeId:inviteContextId,demo,demoState:demo&&data?leagueInviteDemoSnapshot(data,inviteDemo,inviteContextId):null,onDemo:simulateInvite,onJourneyRefresh:refresh})
 const pendingInvites=invites.state?.sent.filter(invite=>invite.team_id===team?.id&&invite.status==='pending'&&Date.parse(invite.expires_at)>Date.now())??[]
 const mapInvites=[...pendingInvites.map(invite=>({slot:invite.slot,alias:invite.invitee_name})),...(detail?.reserved_slots??[]).filter(slot=>!pendingInvites.some(invite=>invite.slot===slot)).map(slot=>({slot,alias:'초대 수락 대기'}))]
 const rosterCounts=team&&definition?leagueRecruitmentCounts(team.players,definition.capacity,mapInvites):null
 useEffect(()=>{
  if(!reviewDecision||busy||connection!=='ready')return
  if(stage!=='roster'||selected?.id!==reviewDecision.challengeId||team?.id!==reviewDecision.teamId||!team.is_captain||locked){setReviewDecision(null);return}
  const next=leagueReviewNextStep(team.players,reviewDecision.playerId,reviewSlot)
  if(next.state==='pending')return
  setReviewDecision(null)
  if(next.state==='review'){setReviewOpen(true);setReviewSlot(next.slot)}
  else{setReviewOpen(false);setReviewSlot(null);setStatusReturn({challengeId:selected.id,teamId:team.id})}
 },[reviewDecision,busy,connection,stage,selected?.id,team,locked,reviewSlot])
 useEffect(()=>{
  if(!statusReturn||busy||connection!=='ready')return
  setStatusReturn(null)
  if(stage!=='roster'||selected?.id!==statusReturn.challengeId||team?.id!==statusReturn.teamId||reviewOpen)return
  focusLeagueRecruitmentStatus(rosterStatus.current,window.matchMedia('(prefers-reduced-motion: reduce)').matches)
 },[statusReturn,busy,connection,stage,selected?.id,team?.id,reviewOpen])
 const incomingInviteCount=invites.state?.incoming.filter(invite=>invite.status==='pending'&&Date.parse(invite.expires_at)>Date.now()).length
 function openReview(slot?:string){if(!team?.is_captain||locked)return;setInviteSlot(null);setReviewSlot(slot??null);setReviewOpen(true)}
 function selectRosterSlot(slot:string){setSelectedSlot(slot);const {occupant,requests}=leagueSlotState(team?.players??[],slot);if(team?.is_captain&&!locked&&requests.length){openReview(slot);return}setReviewOpen(false);if(team?.is_captain&&!locked&&!occupant){setInviteSlot(slot);return}setTier(occupant?.is_me?occupant.tier??'':'')}
 function openInvite(invite:LeaguePositionInvite,asRecipient=false,inboxFirst=false){if(demo&&asRecipient)simulateInvite({type:'view_recipient',inviteId:invite.id});setInviteId(inboxFirst?null:invite.id);setInviteChallengeId(inboxFirst?null:invite.challenge_id);setInviteSlot(null);setStage('invite')}
 function returnToCreator(challengeId?:string){if(demo)simulateInvite({type:'view_captain'});if(challengeId){setSelectedId(challengeId);activeDetail.current=challengeId}setFromNotice(false);if(!demo)void load();setDraft(false);setSelectedSlot('');setInviteSlot(null);setStage('roster')}
 function openTeamChat(challengeId:string,teamId:string){if(!demo){router.push(`/chat/league-team/${encodeURIComponent(teamId)}`);return}setSelectedId(challengeId);activeDetail.current=challengeId;setTeamChatId(teamId);setDraft(false);setInviteSlot(null);setStage('team-chat')}
 useEffect(()=>{if(!sport)return;setNotice('');setSelectedId(initialSport===sport?initialChallengeId??null:null);setDraft(demo&&demoFlow==='invites');setSelectedSlot('');setTier('');setReportSent(false);setScheduleSubmitted(false);setPlace('');setInviteDemo(makeLeagueInviteDemo());setRecruitmentDemo(emptyRecruitmentDemo());setLiveDetail(null);setFromNotice(false);activeDetail.current=initialSport===sport&&!initialInviteId?initialChallengeId??null:null;setInviteSlot(null);setInviteId(initialSport===sport?initialInviteId??null:null);setInviteChallengeId(initialSport===sport?initialChallengeId??null:null);if(demo){if(demoFlow==='recruitment'){const fixture=makeLeagueRecruitmentDemo(sport);setData(fixture.journey);setRecruitmentDemo(fixture.recruitment);setConnection('ready');return}setData(makeLeagueDemo(sport,demoRanking,demoFlow==='invites'));setConnection('ready');return}const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[sport,demo,demoRanking,demoFlow,initialSport,initialChallengeId,initialInviteId,load])
 useEffect(()=>{if(stage==='opponents'&&selected&&selected.status!=='recruiting'&&team?.is_mine){if(selected.status==='completed')setStage('result');else if(demo)setStage('match');else router.push(`/chat/rooms/league_match/${encodeURIComponent(selected.id)}`)}},[selected,stage,team?.is_mine,demo,router])
 function simulate(action:LeagueDemoAction){if(!demo||!data||!selected)return;setData(advanceLeagueDemo(data,action,selected.id));if(action.type==='captain_accept'){setScheduleSubmitted(false);setScheduleSnapshot(null)}}
 function simulateRecruitment(action:LeagueRecruitmentDemoAction){if(!demo||!data)return;const next=advanceRecruitmentDemo(data,recruitmentDemo,action);setData(next.journey);setRecruitmentDemo(next.recruitment)}
 function createTeamDraft(){if(demo&&recruitmentDemo.captainChallengeId)simulateRecruitment({type:'view_member',challengeId:recruitmentDemo.captainChallengeId});activeDetail.current=null;setSelectedId(null);setLiveDetail(null);setFromNotice(false);setDraft(true);setSelectedSlot('');setTier('');setTitle('');setStage('roster')}
 function openRecruitmentTeam(id:string,noticeEntry=false,slot?:string){if(demo&&recruitmentDemo.captainChallengeId)simulateRecruitment({type:'view_member',challengeId:recruitmentDemo.captainChallengeId});activeDetail.current=id;setSelectedId(id);setDraft(false);setLiveDetail(null);setFromNotice(noticeEntry);setSelectedSlot(slot??'');setTier('');setNotice('');setStage('roster');if(!demo)void load()}
 async function cancelRequest(){if(!selected||!team)return;if(demo){simulateRecruitment({type:'cancel_request',challengeId:selected.id});return}await operation(async()=>{await challengeCommand('/roster',{team_id:team.id},'DELETE');await load()})}
 async function decideRequest(player:JourneyPlayer,accept:boolean){if(!selected||!team?.is_captain||!sport||locked||player.status!=='requested')return;await operation(async()=>{if(demo)simulateRecruitment({type:accept?'approve':'reject',challengeId:selected.id,rosterId:player.id});else{if(accept)await challengeCommand(`/roster/${player.id}/accept`,{});else await leagueRecruitmentCommand('reject',{sport,team_id:team.id,roster_id:player.id,expected_revision:selected.revision},crypto.randomUUID());await Promise.all([load(),invites.refresh()])}setReviewDecision({challengeId:selected.id,teamId:team.id,playerId:player.id});setNotice(accept?'신청을 승인했어요. 확정 인원과 팀 지도에 반영됐어요.':'신청을 거절했어요. 검토 대기에서 제외됐어요.')})}
 useEffect(()=>{setScheduleSubmitted(false);setScheduleSnapshot(null)},[selected?.id])
 useEffect(()=>{if(!demo&&selected&&!selected.schedule_proposals.some(proposal=>proposal.is_mine))setScheduleSubmitted(false)},[demo,selected])
 async function operation(action:()=>Promise<unknown>){if(operationMutation.current||busy||connection!=='ready')return null;operationMutation.current=true;setBusy(true);setNotice('');try{return await action()}catch(error){setNotice(recruitmentError(error));return null}finally{operationMutation.current=false;setBusy(false)}}
 async function journeyCommand(action:string,args:Record<string,unknown>){return readResponse(await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,args})}),'journey')}
 async function leagueCommand(action:string,args:Record<string,unknown>){return readResponse(await fetch('/api/community/department/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,args})}),'league')}
 async function challengeCommand(suffix:string,args:Record<string,unknown>,method='POST'){
  if(!selected)throw new Error('challenge_required')
  const response=await fetch(`/api/community/department/challenges/${selected.id}${suffix}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...args,expected_revision:selected.revision,idempotency_key:crypto.randomUUID()})})
  const body=await response.json().catch(()=>null);if(!response.ok||!body)throw new Error(typeof body?.error==='string'?body.error:'challenge_failed');return body
 }
 async function saveSlot(event:FormEvent){event.preventDefault();if(slotMutation.current||busy||!sport||!selectedSlot||!tier||detail?.reserved_slots.includes(selectedSlot)&&me?.slot!==selectedSlot||selected&&me?.status!=='accepted'&&!team?.may_join)return
  slotMutation.current=true;setBusy(true);const targetId=selected?.id,version=detailGeneration.current
  try{
   let currentNotice=detail?.notice
   if(fromNotice){
    if(isRecruitmentNoticeClosed(currentNotice)){setNoticeTick(value=>value+1);setNotice('마감된 모집 소식이에요. 우리 과 팀 목록에서 현재 모집 상태를 확인해 주세요.');await refresh();return}
    if(!demo&&selected){const current=await readLeagueRecruitmentDetail(sport,selected.id);if(activeDetail.current!==targetId||version!==detailGeneration.current)return;setLiveDetail(current);setData(previous=>previous?{...previous,challenges:[current.challenge,...previous.challenges.filter(challenge=>challenge.id!==current.challenge.id)]}:previous);currentNotice=current.notice;if(current.challenge.revision!==selected.revision&&!isRecruitmentNoticeClosed(currentNotice)){setNotice('팀 구성이 바뀌었어요. 새 지도를 확인한 뒤 다시 신청해 주세요.');return}}
    if(isRecruitmentNoticeClosed(currentNotice)){setNoticeTick(value=>value+1);setNotice('마감된 모집 소식이에요. 이 소식에서는 참가 신청을 받지 않아요.');return}
   }
   if(demo){if(!selected&&data){const next=advanceLeagueDemo(data,{type:'create_team',slot:selectedSlot,tier,title:title.trim()||`${data.my_department} ${definition?.label}`});setData(next);setSelectedId(next.challenges[0].id);activeDetail.current=next.challenges[0].id;setDraft(false);setSelectedSlot('');setTier('')}else if(me?.status==='accepted')simulate({type:'profile',slot:selectedSlot,tier});else simulate({type:'request',slot:selectedSlot,tier,...applicationIntro});return}
   const args={sport,slot:selectedSlot,tier,idempotency_key:crypto.randomUUID()},action=!selected?'create':me?.status==='accepted'?'profile':'join';const result=await journeyCommand(action,!selected?{...args,title:title.trim()||`${data?.my_department} ${definition?.label}`}:{...args,challenge_id:selected.id,team_id:team?.id,expected_revision:selected.revision,...(action==='join'?applicationIntro:{})}) as {challenge_id?:string};if(!result?.challenge_id)throw new Error('missing_created_challenge');if(targetId&&activeDetail.current!==targetId)return;setSelectedId(result.challenge_id);activeDetail.current=result.challenge_id;setDraft(false);await load();setNotice(action==='join'?'journey.awaitApproval':'challenge.saved')
  }catch(error){setNotice(recruitmentError(error));if(fromNotice)await refresh()}finally{slotMutation.current=false;setBusy(false)}
 }
 async function findOpponent(){setStage('opponents')}
 async function adoptSchedule(proposal:JourneyScheduleProposal){if(demo)return;await operation(async()=>{await challengeCommand('/schedule',{scheduled_at:proposal.scheduled_at,ends_at:proposal.ends_at,place_name:proposal.place_name});setScheduleSubmitted(true);await refresh()})}
 async function submitSchedule(event:FormEvent){event.preventDefault();if(Date.parse(endsAt)<=Date.parse(startsAt)){setNotice('challenge.failed');return}if(demo){setScheduleSnapshot({startsAt:new Date(startsAt).toISOString(),endsAt:new Date(endsAt).toISOString(),place:place.trim()});setScheduleSubmitted(true);return}await operation(async()=>{await challengeCommand('/schedule',{scheduled_at:new Date(startsAt).toISOString(),ends_at:new Date(endsAt).toISOString(),place_name:place});setScheduleSubmitted(true);await refresh()})}
 async function submitResult(event:FormEvent){event.preventDefault();if(demo){simulate({type:'result',own:ownScore,opponent:opponentScore});return}await operation(async()=>{await challengeCommand('/result',{own_score:ownScore,opponent_score:opponentScore});await load()})}
 const loadTargets=useCallback(async()=>{
  if(!selected||stage!=='report')return
  setTargetError(false)
  if(demo){const opponent=selected.teams.find(other=>other.id!==team?.id);setTargets(opponent?.players.map(player=>({id:player.id,alias:player.alias,position:player.position??'',slot:player.slot}))??[]);return}
  try{const value=await readResponse(await fetch(`${endpoint}?action=report_targets&challenge_id=${selected.id}`,{cache:'no-store'}),'journey');if(!Array.isArray(value)||value.length>20||value.some(v=>!v||typeof v.id!=='string'||typeof v.alias!=='string'||typeof v.position!=='string'||!(v.slot===null||typeof v.slot==='string')))throw new Error('invalid_targets');setTargets(value as Target[])}catch{setTargets(null);setTargetError(true)}
 },[demo,selected,stage,team?.id])
 useEffect(()=>{if(stage==='report')void loadTargets()},[stage,loadTargets])
 async function submitReport(event:FormEvent){event.preventDefault();if(!selected||!selectedTarget)return;if(demo){setReportSent(true);return}await operation(async()=>{await leagueCommand('report',{challenge_id:selected.id,target_player_id:selectedTarget,reason});setReportSent(true);return true})}
 function go(next:Stage,targetId?:string){const matchId=targetId??selected?.id;if(!demo&&next==='match'&&matchId){router.push(`/chat/rooms/league_match/${encodeURIComponent(matchId)}`);return}if(coordinationOnly&&matchId){router.push(`/meetups/league?sport=${sport}&challenge=${encodeURIComponent(matchId)}${next==='result'?'&panel=result':''}`);return}if(next==='roster'&&(targetId||selected?.id)){openRecruitmentTeam(targetId??selected!.id);return}if(next==='league'||next==='recruitment'){activeDetail.current=null;setFromNotice(false)}if(targetId)setSelectedId(targetId);else if(selected&&['match','result','report'].includes(next))setSelectedId(selected.id);setNotice('');setStage(next)}
 const stageKeys:Stage[]=['league','roster','opponents','match','result','report']
 const targetTeamMissing=exactTeam&&!team
 const ready=connection==='ready'&&!!data&&!targetTeamMissing
 const blankTeam:JourneyTeam={id:'draft',department:data?.my_department??'',is_mine:false,is_captain:true,may_join:true,ready:false,waiting:false,gap:200,score:null,players:[]}
 const hasEnded=!!selected?.ends_at&&Date.parse(selected.ends_at)<=Date.now()

 const schedulePanel=selected&&team&&sport?(selected.status==='opponent_pending'?<section className={styles.actionCard}><h2>{t('journey.schedule')}</h2>{!demo?<button type="button" className={styles.textButton} disabled={busy} onClick={()=>void load()}>{t('challenge.retry')}</button>:null}{selected.schedule_proposals.map(proposal=><div key={proposal.team_id} className={styles.notice}><strong>{t(proposal.is_mine?'journey.myScheduleProposal':'journey.opponentScheduleProposal')}</strong><p>{proposal.place_name}</p><p>{new Date(proposal.scheduled_at).toLocaleString(locale)} — {new Date(proposal.ends_at).toLocaleString(locale)}</p>{!demo&&!proposal.is_mine&&team.is_captain?<button type="button" className={styles.secondary} disabled={busy} onClick={()=>void adoptSchedule(proposal)}>{t('journey.adoptSchedule')}</button>:null}</div>)}{team.is_captain?<form onSubmit={submitSchedule} className={styles.compactForm}><label>{t('journey.startsAt')}<input required type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>{t('journey.endsAt')}<input required type="datetime-local" min={startsAt} value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label><label>{t('journey.place')}<input required minLength={2} maxLength={80} value={place} onChange={event=>setPlace(event.target.value)} placeholder={sport==='lol'?'PC café':'Campus pitch'}/></label><button type="submit" className={styles.primary} disabled={busy}>{t('journey.confirmSchedule')}</button></form>:<p>{t('journey.captainConsent')}</p>}{scheduleSubmitted?<p className={styles.notice}>{t('journey.scheduleWaiting')}{demo&&scheduleSnapshot?<><br/>{scheduleSnapshot.place} · {new Date(scheduleSnapshot.startsAt).toLocaleString(locale)}</>:null}</p>:null}{demo&&scheduleSubmitted&&scheduleSnapshot?<button type="button" className={styles.secondary} onClick={()=>simulate({type:'schedule',...scheduleSnapshot})}>{t('journey.demoSchedule')}</button>:null}</section>:<section className={styles.actionCard}><span className={styles.eyebrow}>{t('journey.scheduleConfirmed')}</span><h2>{selected.place_name}</h2><p>{selected.scheduled_at?new Date(selected.scheduled_at).toLocaleString(locale):''}</p><p className={styles.small}>{t('challenge.rosterLocked')}</p>{demo&&selected.status==='scheduled'&&!hasEnded?<button type="button" className={styles.primary} onClick={()=>{simulate({type:'finish'});go('result')}}>{t('journey.demoFinish')} →</button>:hasEnded||selected.status==='completed'?<button type="button" className={styles.primary} onClick={()=>go('result')}>{t('journey.stage.result')} →</button>:<p className={styles.notice}>{t('journey.resultAfterEnd')}</p>}</section>):null
 if(coordinationOnly)return <section className={styles.matchStage}>{notice?<p className={styles.error} role="alert">{t(notice)}</p>:null}{ready&&selected&&team?schedulePanel:<div role="status" className={styles.connection}><p>경기 약속을 확인하지 못했어요.</p><button type="button" className={styles.secondary} onClick={()=>void load()}>다시 확인</button></div>}</section>

 if(demo&&['team-chat','team-chat-list','team-map'].includes(stage)&&(!chatAllowed||!chatTeam||!chatChallenge))return <main className={styles.page}><div className={styles.shell}><h1>체험 참여 상태를 다시 확인해 주세요</h1><p>개발 중 새로고침으로 예시 팀이 초기화되었어요. 실제 계정의 참여 상태가 아닙니다.</p><button type="button" className={styles.primary} onClick={()=>{setStage('roster');setDraft(true)}}>예시 팀 다시 만들기</button></div></main>
 if(demo&&stage==='team-chat'&&teamChatId&&demoChatTransport)return <LeagueTeamChat teamId={teamChatId} demo={{ownerId:chatOwner,transport:demoChatTransport,onBack:()=>setStage('team-chat-list'),onMap:()=>{setSelectedId(chatChallenge!.id);setDraft(false);setSelectedSlot('');setStage(inviteDemo.viewer==='recipient'?'team-map':'roster')}}}/>
 if(demo&&stage==='team-chat-list')return <main className={styles.page}><div className={styles.shell}><header className={styles.topbar}><button type="button" aria-label="리그 화면으로 돌아가기" onClick={()=>setStage(inviteDemo.viewer==='recipient'?'team-map':'roster')}><ArrowLeft size={22}/></button><span>채팅</span></header><p className={styles.demo}>체험 중 합류한 우리 팀의 대화예요.</p><SocialChatDirectory rooms={chatAllowed&&chatTeam&&chatChallenge&&sport?[{kind:'league_team',id:chatTeam.id,title:leagueTeamName(chatTeam,chatChallenge.title),affiliation:`${chatTeam.department} · ${LEAGUE_SPORTS[sport].label}`,member_count:chatTeam.players.filter(player=>player.status==='accepted').length,writable:true,updated_at:new Date().toISOString()}]:[]} onOpen={()=>setStage('team-chat')}/></div></main>
 if(demo&&stage==='team-map'&&chatTeam&&chatChallenge&&sport&&chatAllowed)return <main className={`${styles.page} ${styles.recruitmentPage} ${styles.rosterPage}`}><div className={styles.shell}><header className={styles.topbar}><button type="button" aria-label="우리 팀 채팅으로 돌아가기" onClick={()=>setStage('team-chat')}><ArrowLeft size={22}/></button><span>{leagueTeamName(chatTeam,chatChallenge.title)}</span></header><div className={styles.teamChatEntry}><div><strong>{chatTeam.department} · 내 팀 지도</strong><span>{chatTeam.players.filter(player=>player.status==='accepted').length}/{LEAGUE_SPORTS[sport].capacity}명 확정 · 예시 수신자</span></div><button type="button" className={styles.primary} onClick={()=>setStage('team-chat')}>우리 팀 채팅 →</button></div><RosterMap sport={sport} players={chatTeam.players.filter(player=>player.status==='accepted').map(player=>({...player,is_me:player.id===chatOwner}))} selected={chatViewer?.slot??''} onSelect={()=>{}} readOnly/><button type="button" className={styles.textButton} onClick={()=>returnToCreator(chatChallenge.id)}>예시 주장으로 돌아가기 →</button></div></main>

 return <main ref={stageStart} className={`${styles.page} ${['recruitment','publish','roster'].includes(stage)?styles.recruitmentPage:''} ${stage==='roster'?styles.rosterPage:''} ${demoFlow==='invites'||stage==='invite'?styles.invitePage:''}`} data-department-league-journey={demo?'rehearsal':'live'}><div className={styles.shell}>
  <header className={styles.topbar}><button type="button" onClick={()=>stage==='sport'?router.push('/meetups/challenges'):go(stage==='league'?'sport':stage==='roster'?'recruitment':stage==='publish'?'roster':'league')} aria-label={stage==='sport'?'학과 대항전으로 돌아가기':stage==='league'?'종목 다시 고르기':stage==='roster'?'우리 과 팀 목록으로 돌아가기':stage==='publish'?'팀 지도로 돌아가기':'종목 순위로 돌아가기'}><ArrowLeft size={22} aria-hidden="true"/></button><span>{stage==='recruitment'?'우리 과 팀 찾기':stage==='roster'?(team?leagueTeamName(team,selected?.title):'새 팀 만들기'):stage==='publish'?'우리 과 모집 소식':'QUANTUM · CAMPUS LEAGUE'}</span>{sport&&['recruitment','roster','publish'].includes(stage)?<div className={styles.headerInbox}><LeagueInviteBell controller={invites} demo={demo} onOpen={()=>{setInviteId(null);setInviteChallengeId(null);setStage('invite')}}/></div>:<Link href="/meetups">{t('challenge.back')}</Link>}</header>
  {demo&&demoFlow==='league'?<p className={styles.demo} role="note">{t('journey.demo')}</p>:null}
  {sport&&!demo?<div className={styles.receivedInviteShortcut}><button type="button" onClick={()=>{setInviteId(null);setInviteChallengeId(null);setStage('invite')}}>받은 포지션 초대 {incomingInviteCount??'확인 중'}<span>→</span></button></div>:null}
  {sport&&['league','recruitment','roster'].includes(stage)?<section className={styles.inviteHint} aria-label="합류 대기판"><strong>팀은 아직 없어도, 같이 할 준비는 됐어요.</strong><p>원하는 포지션으로 나를 등록하거나, 우리 팀에 필요한 사람을 찾아보세요.</p><Link className={styles.secondary} href={`/meetups/${demo?'dev-candidates':'candidates'}?kind=league&key=${sport}`}>{demo?'합류 대기판 체험':'합류 대기판 열기'} →</Link>{!demo&&process.env.NODE_ENV==='development'?<Link className={styles.back} href={`/meetups/dev-candidates?kind=league&key=${sport}`}>예시로 흐름 둘러보기 · 실제 등록 아님</Link>:null}</section>:null}
  {sport?<div className={`${styles.inviteToolbar} ${['recruitment','roster','publish'].includes(stage)?styles.inlineInvites:''}`}>{!['recruitment','roster','publish'].includes(stage)?<LeagueInviteBell controller={invites} demo={demo} onOpen={()=>{setInviteId(null);setInviteChallengeId(null);setStage('invite')}}/>:null}{demo&&inviteDemo.records.length>0?<div className={styles.demoRoles}><span>예시 {inviteDemo.viewer==='captain'?'주장':'수신자'}</span>{inviteDemo.viewer==='recipient'?<button type="button" onClick={()=>returnToCreator(inviteChallengeId??undefined)}>주장으로 →</button>:inviteDemo.records.some(invite=>invite.status==='pending')?<button type="button" onClick={()=>openInvite(inviteDemo.records.find(invite=>invite.status==='pending')!,true,true)}>수신 알림 보기 →</button>:null}</div>:null}</div>:null}
  {stage==='sport'?<><div className={styles.intro}><span className={styles.eyebrow}>{t('challenge.title')}</span><h1>{t('journey.headline')}</h1><p>{t('journey.intro')}</p></div><div className={styles.sports}>{(Object.keys(LEAGUE_SPORTS)as LeagueSport[]).map(key=><button key={key} type="button" className={styles.sportCard} onClick={()=>{setSport(key);go('league')}}><Image src={LEAGUE_SPORTS[key].photo} alt="" fill sizes="(max-width: 760px) 100vw, 33vw"/><span><small>{key==='lol'?'SUMMONER’S RIFT':key==='futsal'?'SMALL SIDE':'FULL PITCH'}</small><strong>{t(`journey.${key}`)}</strong><i>{LEAGUE_SPORTS[key].capacity} vs {LEAGUE_SPORTS[key].capacity} <b>→</b></i></span></button>)}</div><p className={styles.footnote}>{t('journey.overwatch')}</p></>:definition&&sport?<>
   {!['recruitment','publish'].includes(stage)?<div className={styles.stepTitle}><span className={styles.eyebrow}>{t(`journey.${sport}`)}{stage==='invite'?'':` · ${Math.max(1,stageKeys.indexOf(stage)+1)} / 6`}</span><h1>{stage==='recruitment'?'우리 과 팀 찾기':stage==='publish'?'학생 모집 소식':stage==='invite'?'받은 포지션 초대':stage==='roster'&&draft?'내 자리부터, 새 팀 만들기':stage==='match'?'경기 채팅':stage==='opponents'?'대기 팀 둘러보기':t(`journey.stage.${stage}`)}</h1>{!['invite','recruitment','publish'].includes(stage)?<div className={styles.progress} aria-label={t(`journey.stage.${stage}`)}>{stageKeys.map(key=><span key={key} className={stageKeys.indexOf(key)<=stageKeys.indexOf(stage)?styles.progressActive:''}/>)}</div>:null}</div>:null}
   {notice?<p className={styles.error} role="status">{t(notice)}</p>:null}
   {!ready?<section className={styles.connection} aria-live="polite"><h2>{t(connection==='loading'?'challenge.loading':'journey.connectionError')}</h2>{connection==='error'||targetTeamMissing?<button type="button" className={styles.secondary} onClick={()=>void load()}>{t('challenge.retry')}</button>:null}<p>{t('journey.initialPolicy')}</p><strong>1000</strong><small>{t('journey.policyOnly')}</small></section>:null}
   {ready&&stage==='league'?<section className={styles.league}>
    <p className={styles.honorsContext}>{data.month} · {data.my_department}</p>
    <LeagueHonors rows={rows} monthly={monthly} onJoin={()=>go('recruitment')} />
    <div className={styles.tableCard}><div className={styles.rowBetween}><div className={styles.tabs}><button type="button" aria-pressed={!monthly} onClick={()=>setMonthly(false)}>{t('journey.allDepartments')}</button><button type="button" aria-pressed={monthly} onClick={()=>setMonthly(true)}>{t('journey.monthly')}</button></div><button type="button" disabled={busy} onClick={()=>demo?setNotice('journey.demo'):void load()} className={styles.textButton}>{t('challenge.retry')}</button></div><p className={styles.small}>{t('journey.monthRule')}</p><input className={styles.search} value={search} onChange={event=>setSearch(event.target.value)} aria-label={t('journey.searchDept')} placeholder={t('journey.searchDept')}/>
    <div className={styles.tableHead}><span>{t('journey.department')}</span><span>{t('journey.leaguePoints')}</span><span>{t('journey.record')}</span></div><ol className={styles.table}>{visibleRows.map(row=><li key={row.department} className={row.is_me?styles.myRow:undefined} data-honor-rank={row.played>0&&row.rank!==null&&row.rank<=3?row.rank:undefined}><div><b className={styles.rankNumber}>{row.played>0&&row.rank!==null&&row.rank<=3?<Medal size={16} aria-hidden="true"/>:null}{row.rank??'—'}</b><strong>{row.department}{row.is_me?<small>{t('challenge.myDept')}</small>:null}</strong></div><strong>{row.points}</strong><span>{row.played} · {row.wins}/{row.draws}/{row.losses}</span></li>)}</ol>{visibleRows.length===0?<p className={styles.empty}>{t('journey.noMonthly')}</p>:null}<p className={styles.small}>{t('journey.pointsProposal')}</p></div>
    <button type="button" className={styles.primary} onClick={()=>go('recruitment')}>우리 과 팀 찾기 <span>→</span></button>
    {data.challenges.filter(c=>c.teams.some(team=>team.is_mine)).map(c=><button key={c.id} type="button" className={styles.resume} onClick={()=>c.status==='recruiting'?go('roster',c.id):go(c.status==='completed'?'result':'match',c.id)}><span>{leagueTeamName(c.teams.find(team=>team.is_mine)!,c.title)}</span><strong>{c.status==='recruiting'?'우리 팀 모집 이어가기':t(c.status==='completed'?'journey.stage.result':'journey.resume')} →</strong></button>)}
   </section>:null}
   {ready&&stage==='recruitment'?<LeagueRecruitment browseState={recruitmentViews[sport]} onBrowseStateChange={view=>setRecruitmentViews(current=>({...current,[sport]:view}))} sport={sport} demo={demo} journey={data} recruitment={recruitmentDemo} reservations={reservations} onSelect={openRecruitmentTeam} onCreate={createTeamDraft} onBack={()=>go('league')}/>:null}
   {ready&&stage==='publish'&&detail?<LeagueRecruitmentNoticeForm key={detail.team_id} detail={detail} demo={demo} onDemo={simulateRecruitment} onRefresh={refresh} onBack={()=>setStage('roster')}/>:null}
   {ready&&stage==='roster'?<>
    <details className={styles.teamSwitcher}><summary>다른 우리 과 팀 보기</summary><button type="button" className={styles.textButton} onClick={()=>go('recruitment')}>← 우리 과 팀 찾기</button><div className={styles.teamChoices}>{data.challenges.filter(c=>c.status!=='completed'&&c.teams.some(team=>team.department===data.my_department&&team.players.length>0)).map(c=><button key={c.id} type="button" aria-pressed={!draft&&selected?.id===c.id} onClick={()=>openRecruitmentTeam(c.id)}>{leagueTeamName(c.teams.find(t=>t.department===data.my_department)!,c.title)}</button>)}<button type="button" aria-pressed={draft||!selected} onClick={createTeamDraft}>＋ {t('journey.newTeam')}</button></div></details>
    {team?<LeagueRecruitmentStatus team={team} capacity={definition.capacity} pendingInvites={mapInvites} locked={locked} busy={busy} statusRef={rosterStatus} onReview={()=>openReview()} onOpponent={()=>void findOpponent()}/>:null}
    {isTeamMember&&team&&selected?<div className={styles.teamChatEntry}><div><strong>우리 팀 채팅</strong><span>확정된 팀원끼리 인사하고 가능한 시간을 이야기해요.</span></div><button type="button" className={styles.primary} onClick={()=>openTeamChat(selected.id,team.id)}>우리 팀 채팅 →</button></div>:null}
    <div className={styles.sceneGrid}><RosterMap sport={sport} players={(team??blankTeam).players} selected={selectedSlot} inviteMode={!!team?.is_captain&&!locked} pendingInvites={mapInvites} readOnly={!!noticeClosed||busy} onSelect={selectRosterSlot}/><section className={styles.actionCard}><span className={styles.eyebrow}>{data.my_department}</span><h2>{team?leagueTeamName(team,selected?.title):t('journey.newTeam')}</h2><p className={styles.small}>{rosterCounts?.full?'정원을 채웠어요. 내 자리와 팀 정보를 확인해요.':team?.is_captain?'검토 대기 자리는 신청자를 확인하고, 빈자리에는 친구를 초대해요.':me?.status==='accepted'?'내 자리를 눌러 내 정보를 확인하고 바꿀 수 있어요.':me?.status==='requested'?'신청 결과를 기다리고 있어요. 승인되면 확정 인원에 반영돼요.':t('journey.slotHint')}</p>
     {team?<p className={styles.score}>팀 합계 {leagueTeamSum(team).toLocaleString()} <small>· 참가자 자기 입력 점수</small></p>:null}
     {reviewOpen&&team?.is_captain&&!locked?<div ref={reviewPanel} tabIndex={-1} className={styles.reviewPanel}><LeagueRequestReview sport={sport} team={team} slot={reviewSlot} busy={busy} message={notice} onSelectAll={()=>setReviewSlot(null)} onClose={()=>setReviewOpen(false)} onDecide={(player,accept)=>void decideRequest(player,accept)}/></div>:locked?<p className={styles.notice}>{t('challenge.rosterLocked')}</p>:noticeClosed?<p className={styles.notice}>마감된 모집 소식이에요. 이 소식에서는 참가 신청을 받지 않아요.</p>:captainPreview?<p className={styles.notice}>{rosterCounts?.requested?'예시 주장으로 신청을 검토하고 있어요. 승인 전에는 확정 인원에 포함되지 않아요.':'검토할 신청이 없어요. 지도와 확정 인원에서 처리 결과를 확인해요.'}</p>:me?.status==='requested'?<div className={styles.notice}><strong>{t('journey.awaitApproval')}</strong><button type="button" className={styles.secondary} disabled={busy} onClick={()=>void cancelRequest()}>참가 신청 취소</button>{demo&&demoFlow==='recruitment'?<button type="button" className={styles.secondary} onClick={()=>simulateRecruitment({type:'view_captain',challengeId:selected!.id})}>예시 주장으로 신청 검토 →</button>:demo?<button type="button" className={styles.secondary} onClick={()=>simulate({type:'approve'})}>{t('journey.demoApprove')}</button>:null}</div>:selectedSlot&&team?.players.some(p=>p.slot===selectedSlot&&p.status==='accepted'&&!p.is_me)?<p className={styles.notice}>{t('journey.occupied')}</p>:selectedSlot&&detail?.reserved_slots.includes(selectedSlot)&&!team?.is_captain?<p className={styles.notice}>이 자리는 친구의 초대 수락을 기다리고 있어요. 다른 빈자리를 골라 주세요.</p>:team&&!me&&!team.may_join&&!team.is_captain?<p className={styles.notice}>지금은 이 팀에 참가 신청할 수 없어요. 현재 팀 상태를 새로고침해 주세요.</p>:team?.is_captain&&rosterCounts?.full&&selectedSlot!==me?.slot?<p className={styles.notice}>팀 구성이 완료됐어요. 위에서 상대 팀을 직접 골라 제안할 수 있어요.</p>:team?.is_captain&&me?.status==='accepted'&&selectedSlot!==me.slot?<div className={styles.inviteHint}><strong>함께할 친구는 어느 자리인가요?</strong><p>지도에서 빈자리를 누르면 친구 목록이 열려요.</p><small>친구가 자기 티어를 고르고 수락하면 바로 팀원이 돼요.</small></div>:<form onSubmit={saveSlot} className={styles.compactForm}>
      {!selected?<label>{t('journey.teamName')}<input value={title} maxLength={80} placeholder={`${data.my_department} ${definition.label}`} onChange={event=>setTitle(event.target.value)}/></label>:null}
      <label>{t('challenge.position')}<span className={styles.chosenRole}>{definition.slots.find(slot=>slot.key===selectedSlot)?.label??t('journey.selectOnMap')}</span></label>{sport==='lol'?<LeagueTierPicker value={tier} onChange={setTier} disabled={busy} label={t('challenge.tier')} getLabel={value=>t(`challenge.${value}`)}/>:<label>{t('challenge.tier')}<select required disabled={busy} value={tier} onChange={event=>setTier(event.target.value)}><option value="">{t('journey.selectTier')}</option>{sportTiers(sport).map(value=><option key={value} value={value}>{t(`challenge.${value}`)}</option>)}</select></label>}<p className={styles.small}>{t(sport==='lol'?'challenge.notVerified':'journey.sportSelfReport')}</p>
      {selected&&me?.status!=='accepted'?<LeagueApplicationIntro value={applicationIntro} onChange={setApplicationIntro} disabled={busy}/>:null}
      <button className={styles.primary} disabled={busy||!selectedSlot||!tier||!!noticeClosed||!!selected&&me?.status!=='accepted'&&!team?.may_join||!!detail?.reserved_slots.includes(selectedSlot)&&me?.slot!==selectedSlot} type="submit">{!selected?'이 자리로 팀 만들기':me?.status==='accepted'?t('challenge.saveProfile'):'이 자리로 신청하기'}</button>
     </form>}
     {me?.status==='requested'?<LeagueApplicationSummary value={me.application_intro}/>:null}
     {captainPreview?<button type="button" className={styles.secondary} onClick={()=>simulateRecruitment({type:'view_member',challengeId:selected!.id})}>신청자 예시로 돌아가기 →</button>:null}
     {team?.ready&&!locked?<label>{t('challenge.gap')}<select value={gap} disabled={busy||!team.is_captain||(!demo&&team.waiting)} onChange={event=>setGap(Number(event.target.value)as 200|300)}><option value={200}>{t('challenge.gapValue',{gap:200})}</option><option value={300}>{t('challenge.gapValue',{gap:300})}</option></select></label>:null}
     {!locked&&!(team?.is_captain&&rosterCounts?.full)?<button type="button" disabled={busy} className={styles.secondary} onClick={()=>void findOpponent()}>대기 팀·주장 관리 →</button>:null}{team&&!team.ready?<p className={styles.small}>{t(locked?'challenge.fixedTeamIncomplete':'journey.completeTeam')}</p>:null}{team?.ready&&!demo&&!team.is_captain?<p className={styles.small}>{t('journey.captainConsent')}</p>:null}
     {team?.is_captain&&!locked&&detail?<button type="button" className={styles.primary} onClick={()=>setStage('publish')}>{detail.notice?'우리 과 모집 소식 관리':'우리 과에 팀원 모집하기'} →</button>:null}
     {!demo?<button type="button" className={styles.textButton} disabled={busy} onClick={()=>void load()}>팀 지도 새로고침</button>:null}
     {locked?<button type="button" className={styles.primary} onClick={()=>go(hasEnded||selected?.status==='completed'?'result':'match')}>{t('journey.resume')} →</button>:null}
     {me?.status==='accepted'&&!demo&&!team?.is_captain?<button type="button" disabled={busy} className={styles.textButton} onClick={()=>void operation(async()=>{await challengeCommand('/roster',{team_id:team?.id},'DELETE');await load();go('league')})}>{t('journey.leave')}</button>:null}
    </section></div>
    {team&&selected&&inviteSlot?<LeaguePositionInviteSheet key={`${team.id}:${inviteSlot}`} sport={sport} slot={inviteSlot} teamId={team.id} challengeId={selected.id} revision={selected.revision} controller={invites} demo={demo} onClose={()=>{setInviteSlot(null);setSelectedSlot('')}} onViewRecipient={invite=>openInvite(invite,true)}/>:null}
   </>:null}
   {stage==='invite'?(inviteId?<LeagueInviteReceiver key={inviteId} sport={sport} inviteId={inviteId} controller={invites} demo={demo} renderMap={(players,slot,pending)=><RosterMap sport={sport} players={players} selected={slot} pendingInvites={pending} readOnly compact onSelect={()=>{}}/>} onBack={()=>{setInviteId(null);setInviteChallengeId(null)}} onJoined={openTeamChat}/>:<LeagueInviteInbox controller={invites} onSelect={invite=>openInvite(invite)} onBack={()=>go('league')}/>):null}
   {ready&&stage==='opponents'?<LeagueLobby sport={sport} gap={gap} state={data} own={team} revision={selected?.revision??0} demo={demo} onDemo={simulate} onRoster={()=>go('roster')} onPaired={id=>{if(id){activeDetail.current=id;setSelectedId(id);if(!demo)void load()}setNotice('');go('match',id)}} onRefresh={refresh} renderRoster={(players,selected,onSelect)=><RosterMap sport={sport} players={players} selected={selected} onSelect={onSelect}/>} />:null}
   {ready&&stage==='match'&&selected&&team?<section className={styles.matchStage}><MatchTeams teams={selected.teams} capacity={definition.capacity}/>{demo?<p className={styles.small}>{t('journey.demoRole')}</p>:null}
    <LeagueMatchChat key={selected.id} challengeId={selected.id} teamNames={selected.teams.map(team=>leagueTeamName(team,selected.title))} demo={demo} scheduled={selected.status!=='opponent_pending'} onRefresh={refresh} schedule={schedulePanel}/>
    {selected.status!=='completed'?<LeagueLobby captainOnly sport={sport} state={data} own={team} revision={selected.revision} demo={demo} onDemo={simulate} onRoster={()=>go('roster')} onPaired={()=>go('match')} onRefresh={refresh} renderRoster={()=>null}/>:null}
    {!demo&&team.is_captain&&selected.status!=='completed'?<button type="button" className={styles.textButton} disabled={busy} onClick={()=>void operation(async()=>{await challengeCommand('/cancel',{reason:'새로운 참가 구성으로 다시 모집하기 위해 취소합니다.'});await load();go('league')})}>{t('journey.cancelRecruitment')}</button>:null}
   </section>:null}
   {ready&&stage==='result'&&selected&&team?<section className={styles.resultStage}><MatchTeams teams={selected.teams} capacity={definition.capacity}/>{selected.status==='completed'&&selected.result?<div className={styles.resultCard}><span className={styles.eyebrow}>{t('journey.resultConfirmed')}</span><strong>{selected.result.first_score} : {selected.result.second_score}</strong><p>{t('challenge.rankNote')}</p><button type="button" className={styles.primary} onClick={()=>{setMonthly(true);go('league')}}>{t('journey.viewRanking')}</button></div>:<section className={styles.actionCard}><h2>{t('challenge.rankNote')}</h2>{team.is_captain?<form onSubmit={submitResult}><div className={styles.scoreInputs}><label>{t('journey.ownScore')}<input type="number" required disabled={demo&&selected.status==='result_pending'} min={0} max={999} value={ownScore} onChange={event=>setOwnScore(Number(event.target.value))}/></label><span>:</span><label>{t('journey.opponentScore')}<input type="number" required disabled={demo&&selected.status==='result_pending'} min={0} max={999} value={opponentScore} onChange={event=>setOpponentScore(Number(event.target.value))}/></label></div><button type="submit" disabled={busy||(!demo&&!hasEnded)||selected.status==='result_pending'&&demo} className={styles.primary}>{t('journey.confirmResult')}</button></form>:<p>{t('journey.captainConsent')}</p>}{selected.status==='result_pending'?<p className={styles.notice}>{t('journey.resultWaiting')}</p>:null}{demo&&selected.status==='result_pending'?<button type="button" className={styles.secondary} onClick={()=>simulate({type:'confirm',own:ownScore,opponent:opponentScore})}>{t('journey.demoResult')}</button>:null}</section>}<button type="button" className={styles.secondary} onClick={()=>{setTargets(null);setSelectedTarget('');setReportSent(false);go('report')}}>{t('challenge.report')} →</button></section>:null}
   {ready&&stage==='report'&&selected?<section className={styles.reportStage}><p className={styles.small}>{t('challenge.reportExplain')}</p>{targetError?<div role="alert" className={styles.error}>{t('challenge.loadError')}<button type="button" onClick={()=>void loadTargets()}>{t('challenge.retry')}</button></div>:targets===null?<p role="status">{t('challenge.loading')}</p>:targets.length?<div className={styles.sceneGrid}><RosterMap sport={sport} players={targets.map(target=>({id:target.id,alias:target.alias,status:'accepted',is_me:false,slot:target.slot,position:target.position,tier:null}))} selected={targets.find(target=>target.id===selectedTarget)?.slot??''} onSelect={slot=>{const target=targets.find(target=>target.slot===slot);if(target)setSelectedTarget(target.id)}} report/><section className={styles.actionCard}>{reportSent?<div role="status" className={styles.notice}><h2>{t('journey.reportSaved')}</h2><p>{t('journey.noAutomaticPenalty')}</p><button type="button" className={styles.secondary} onClick={()=>go('league')}>{t('journey.stage.league')}</button></div>:<form className={styles.compactForm} onSubmit={submitReport}><h2>{t('journey.selectOpponent')}</h2><div className={styles.targetChoices}>{targets.map(target=><button key={target.id} type="button" aria-pressed={selectedTarget===target.id} onClick={()=>setSelectedTarget(target.id)}>{target.slot?.toUpperCase()??t(`challenge.${target.position}`)} · {target.alias}</button>)}</div><label>{t('challenge.reportReason')}<textarea required minLength={10} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="submit" className={styles.primary} disabled={busy||!selectedTarget||reason.trim().length<10}>{t('challenge.report')}</button><p className={styles.small}>{t('journey.noAutomaticPenalty')}</p></form>}</section></div>:<p className={styles.empty}>{t('journey.noTargets')}</p>}</section>:null}
  </>:null}
  <footer className={styles.footer}><p>{t('challenge.privateIdentity')}</p></footer>
 </div></main>
}
export default DepartmentLeagueJourney

export function RosterMap({sport,players,selected,onSelect,report=false,inviteMode=false,pendingInvites=[],readOnly=false,compact=false}:{sport:LeagueSport;players:readonly JourneyPlayer[];selected:string;onSelect:(slot:string)=>void;report?:boolean;inviteMode?:boolean;pendingInvites?:readonly {slot:string;alias:string}[];readOnly?:boolean;compact?:boolean}){
 const{t}=useQuantumLocale(),definition=LEAGUE_SPORTS[sport]
 const Slot=readOnly?'div':'button'
 const focused=players.find(player=>player.slot===selected&&player.status==='accepted')
 return <div className={styles.mapGroup}><div className={`${styles.map} ${compact?styles.compactMap:''} ${sport==='lol'?styles.lolMap:styles.pitchMap}`} aria-label={t('journey.mapLabel')}>
  <Image src={definition.image} alt={t(sport==='lol'?'journey.lolMapAlt':'journey.pitchAlt')} fill sizes="(max-width:760px) 100vw, 520px" priority/>
  {definition.slots.map(slot=>{
   const {occupant,requests,invited}=leagueSlotState(players,slot.key,pendingInvites),count=requests.length
   const label=occupant?.alias??(count?`검토 대기 ${count}명`:invited?invited.alias:inviteMode?'＋ 친구 초대':t('journey.emptySlot'))
   const description=[slot.label,occupant?`확정 · ${occupant.alias}`:count?`검토 대기 ${count}명`:invited?'초대 중':inviteMode?'빈자리 · 친구 초대':t('journey.emptySlot'),occupant?.tier?t(`challenge.${occupant.tier}`):'',occupant&&count?`검토 대기 ${count}명`:'',invited?`${invited.alias} 초대 중 · 인원 확정 전`:''].filter(Boolean).join(' · ')
   return <Slot type={readOnly?undefined:"button"} role={readOnly?"img":undefined} key={slot.key} style={{left:`${slot.x}%`,top:`${slot.y}%`}} className={`${styles.slot} ${occupant?styles.occupied:count?styles.requested:invited?styles.invited:styles.available} ${selected===slot.key?styles.selected:''}`} data-slot-state={occupant?'accepted':count?'requested':invited?'invited':'empty'} aria-pressed={readOnly?undefined:selected===slot.key} aria-label={description} disabled={readOnly?undefined:report&&!occupant} onClick={readOnly?undefined:()=>onSelect(slot.key)}>
    {!compact&&sport!=='lol'?<Shirt className={styles.jersey} size={30} aria-hidden="true"/>:null}{!occupant&&!invited&&!count&&!compact?<Plus className={styles.seatPlus} size={16} aria-hidden="true"/>:null}
    <b>{slot.label}</b><span>{label}</span>{occupant?.tier?sport==='lol'?<LeagueTierBadge tier={occupant.tier} label={t(`challenge.${occupant.tier}`)} size="map" showLabel={false}/>:<small>{t(`challenge.${occupant.tier}`)}</small>:invited?<small>초대 중</small>:count?<small>승인 전</small>:null}
    {occupant&&count>0?<em className={styles.requestCount}>검토 {count}</em>:null}
   </Slot>
  })}
 </div>{focused&&!compact?<div className={styles.focusedPlayer} role="status"><strong>{focused.slot?.toUpperCase()} · {focused.alias}</strong><span>{focused.tier&&sport==='lol'?<LeagueTierBadge tier={focused.tier} label={t(`challenge.${focused.tier}`)} size="detail"/>:focused.tier?t(`challenge.${focused.tier}`):'실력 정보 없음'} · 자기 입력</span></div>:null}</div>
}
function MatchTeams({teams,capacity}:{teams:readonly JourneyTeam[];capacity:number}){return <div className={styles.matchTeams}>{teams.map((team,index)=><div key={team.id}><small>{index===0?'HOME':'AWAY'} · {team.players.filter(p=>p.status==='accepted').length}/{capacity}</small><h2>{leagueTeamName(team)}</h2><small>{team.department}</small><span>팀 합계 {leagueTeamSum(team).toLocaleString()}</span></div>)}</div>}
