import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

function readSource(path: string): string {
  return readFileSync(join(process.cwd(), path), 'utf8')
}

test('match setup pages continue directly to the next setup step from match start', () => {
  const redirectHelper = readSource('lib/client-redirect.ts')
  const personalityPage = readSource('app/profile/personality-preference/page.tsx')
  const schedulePage = readSource('app/profile/schedule/page.tsx')
  const preferencesPage = readSource('app/profile/preferences/page.tsx')

  assert.match(redirectHelper, /function getSequentialMatchStartRedirect/)
  assert.match(redirectHelper, /!redirect\.startsWith\('\/match\/start'\)/)
  assert.match(redirectHelper, /encodeURIComponent\(redirect\)/)
  assert.match(personalityPage, /getSequentialMatchStartRedirect\('\/profile\/schedule'/)
  assert.match(schedulePage, /getSequentialMatchStartRedirect\('\/profile\/preferences'/)
  assert.match(preferencesPage, /getSequentialMatchStartRedirect\('\/profile\/match-card'/)
})

test('dev preview queue status persists from group create to the home task card', () => {
  const devSetup = readSource('lib/dev-match-setup.ts')
  const groupCreatePage = readSource('app/group/create/page.tsx')
  const homeTaskCard = readSource('components/matching/HomeTodayTaskCard.tsx')
  const matchPage = readSource('app/match/page.tsx')

  assert.match(devSetup, /DEV_PREVIEW_GROUP_STATUS_COOKIE/)
  assert.match(devSetup, /function setDevPreviewGroupStatus/)
  assert.match(devSetup, /function getDevPreviewGroupStatusFromClient/)
  assert.match(devSetup, /function setDevPreviewGroupSize/)
  assert.match(devSetup, /function getDevPreviewGroupSizeFromClient/)
  assert.match(devSetup, /DEV_PREVIEW_SOLO_STATUS_COOKIE/)
  assert.match(devSetup, /function setDevPreviewSoloStatus/)
  assert.match(devSetup, /function getDevPreviewSoloStatusFromClient/)

  assert.match(groupCreatePage, /setDevPreviewGroupStatus\('in_pool'\)/)
  assert.match(groupCreatePage, /setDevPreviewGroupStatus\('ready'\)/)
  assert.match(groupCreatePage, /getDevPreviewGroupStatusFromClient\(\)/)
  assert.match(groupCreatePage, /getDevPreviewGroupSizeFromClient\(requestedSize\)/)

  assert.match(homeTaskCard, /getDevPreviewGroupStatusFromClient\(\)/)
  assert.match(homeTaskCard, /getDevPreviewSoloStatusFromClient\(\)/)
  assert.match(homeTaskCard, /setDevPreviewGroupStatus/)
  assert.match(homeTaskCard, /setDevPreviewSoloStatus/)
  assert.match(homeTaskCard, /getDevPreviewGroupSizeFromClient\(DEV_PREVIEW_GROUP\.size\)/)
  assert.match(homeTaskCard, /soloStatus === 'in_pool'/)
  assert.match(homeTaskCard, /href: '\/match\?mode=solo&soloStatus=in_pool'/)
  assert.match(homeTaskCard, /soloStatus === 'matched'/)
  assert.match(homeTaskCard, /href: '\/match\?mode=solo&sampleMatches=1'/)
  assert.match(homeTaskCard, /const isSoloFlow = isSoloQueue \|\| isSoloMatched/)
  assert.match(homeTaskCard, /groupName=\{teamCardName\}/)
  assert.match(homeTaskCard, /status=\{teamCardStatus\}/)
  assert.match(homeTaskCard, /1:1 매칭대기중 - 조건이 맞는 상대를 찾는 중/)
  assert.match(homeTaskCard, /상대 탐색 중/)
  assert.match(homeTaskCard, /if \(loading\) \{/)
  assert.match(homeTaskCard, /href: '\/match'/)
  assert.match(homeTaskCard, /const handleCancelQueue =/)
  assert.match(homeTaskCard, /fetch\('\/api\/match-pool\/cancel'/)
  assert.match(homeTaskCard, /canCancelQueueFromHome/)
  assert.match(homeTaskCard, /const handleCancelActiveMatch =/)
  assert.match(homeTaskCard, /pendingMatch/)
  assert.match(homeTaskCard, /\/api\/matches\/\$\{encodeURIComponent\(pendingMatch\.match_id\)\}\/cancel/)
  assert.match(homeTaskCard, /canCancelActiveMatchFromHome/)
  assert.match(homeTaskCard, /const teamCardAction = canCancelQueueFromHome/)
  assert.match(homeTaskCard, /action=\{teamCardAction\}/)
  assert.match(homeTaskCard, /soloStatus === 'matched'/)
  assert.match(homeTaskCard, /setDevPreviewSoloStatus\('idle'\)/)
  assert.match(homeTaskCard, /1:1 매칭 취소하기/)
  assert.match(homeTaskCard, /매칭 취소하기/)
  assert.doesNotMatch(homeTaskCard, /setGroupStatus\(null\)/)

  assert.match(matchPage, /getDevPreviewGroupStatusFromClient\(\)/)
  assert.match(matchPage, /getDevPreviewSoloStatusFromClient\(\)/)
  assert.match(matchPage, /setDevPreviewSoloStatus\(requestedSoloStatus\)/)
  assert.match(matchPage, /getDevPreviewGroupSizeFromClient\(DEV_PREVIEW_GROUP\.size\)/)
  assert.match(matchPage, /status: previewGroupStatus/)
  assert.match(matchPage, /DEV_PREVIEW_GROUP_MEMBERS\.slice\(0, previewGroupSize\)/)
  assert.match(matchPage, /teamCardName = loading/)
  assert.match(matchPage, /\{loading \? \(/)
})

test('group create shows an app-styled Korean loading shell before client data loads', () => {
  const groupCreatePage = readSource('app/group/create/page.tsx')
  const groupHeader = readSource('components/matching/group-create/GroupHeader.tsx')

  assert.match(groupHeader, /그룹 과팅/)
  assert.doesNotMatch(groupHeader, />\s*Group Match\s*</)
  assert.match(groupCreatePage, /그룹 정보를 준비하는 중/)
  assert.match(groupCreatePage, /현재 함께하는 친구/)
  assert.match(groupCreatePage, /친구 초대와 준비 상태를 불러오고 있어요/)
  assert.match(groupCreatePage, /Array\.from\(\{ length: capacity \}\)/)
})

test('match hub renders opponent cards only after match results exist', () => {
  const matchPage = readSource('app/match/page.tsx')

  assert.match(matchPage, /const visibleMatches = isSoloMode/)
  assert.match(matchPage, /match\.match_mode === 'solo'/)
  assert.match(matchPage, /\(match\.match_mode \?\? 'group'\) === 'group'/)
  assert.match(matchPage, /const currentMatchResult = visibleMatches\[0\]/)
  assert.match(matchPage, /const hasMatchResults = visibleMatches\.length > 0/)
  assert.match(matchPage, /const hasStartedMatching =/)
  assert.match(matchPage, /const effectiveMatchMode: MatchMode = soloBlockedByGroupFlow \? 'group' : matchMode/)
  assert.match(matchPage, /const hasAnyStartedMatching = groupFlowActive \|\| rawSoloFlowActive/)
  assert.match(matchPage, /const shouldShowMatchingPool = !loading && !hasAnyStartedMatching && !hasMatchResults/)
  assert.match(matchPage, /const canCancelActiveQueue = !loading/)
  assert.match(matchPage, /&& hasAnyStartedMatching/)
  assert.match(matchPage, /<QueueControlStrip/)
  assert.match(matchPage, /\{loading \? \(/)
  assert.match(matchPage, /: hasMatchResults \? \(/)
  assert.match(matchPage, /hasStartedMatching && !hasMatchResults/)
  assert.match(matchPage, /<MatchSearchingPrivacyCard[\s\S]+mode=\{effectiveMatchMode\}/)
  assert.match(matchPage, /<MatchSearchingPrivacyCard[\s\S]+canceling=\{cancelingQueue\}/)
  assert.match(matchPage, /<MatchSearchingPrivacyCard[\s\S]+onCancel=\{isSoloMode \? handleCancelSoloQueue : handleCancelGroupQueue\}/)
  assert.match(matchPage, /<PostMatchFlowCard[\s\S]+match=\{currentMatchResult\}/)
  assert.match(matchPage, /\{shouldShowMatchingPool && \(/)
  assert.doesNotMatch(matchPage, /visibleMatches\.map/)
  assert.match(matchPage, /지금은 \{targetLabel\}를 찾는 중이에요/)
  assert.match(matchPage, /가매칭이 도착하기 전까지는/)
  assert.match(matchPage, /!loading && !hasAnyStartedMatching && \(/)
  assert.doesNotMatch(matchPage, /title=\{matches\.length > 0 \?/)
  assert.doesNotMatch(matchPage, /chemi=\{matches\.length > 0 \?/)
  assert.doesNotMatch(matchPage, /chemi=\{70\}/)
})

test('home routes the main matching CTA through the matching hub', () => {
  const homePage = readSource('app/page.tsx')

  assert.match(homePage, /href="\/match"/)
  assert.doesNotMatch(homePage, /href="\/match\/start"/)
  assert.doesNotMatch(homePage, /HomeLockedOpponentNotice/)
  assert.doesNotMatch(homePage, /상대팀 카드는 아직 잠겨 있어요/)
})

test('matching pool uses large match cards without decorative dot clusters', () => {
  const matchingPool = readSource('components/MatchingPool.tsx')

  assert.match(matchingPool, /mode = 'group'/)
  assert.match(matchingPool, /const showSoloPool = mode === 'solo'/)
  assert.match(matchingPool, /const showGroupPool = mode === 'group'/)
  assert.match(matchingPool, /showSoloPool &&/)
  assert.match(matchingPool, /showGroupPool &&/)
  assert.match(matchingPool, /const headline = active/)
  assert.match(matchingPool, /1:1 상대를 찾는 중이에요/)
  assert.match(matchingPool, /이미 큐에 들어가 있어요/)
  assert.match(matchingPool, /1:1 소개팅 매치/)
  assert.match(matchingPool, /href="\/match\/start\?mode=solo"/)
  assert.match(matchingPool, /남자 대기자/)
  assert.match(matchingPool, /여자 대기자/)
  assert.match(matchingPool, /2:2 그룹 매치/)
  assert.match(matchingPool, /3:3 그룹 매치/)
  assert.match(matchingPool, /function QueueCircleCard/)
  assert.match(matchingPool, /function QueueRing/)
  assert.match(matchingPool, /function QueueStat/)
  assert.match(matchingPool, /buildRingGradient/)
  assert.match(matchingPool, /conic-gradient/)
  assert.match(matchingPool, /혼성팀/)
  assert.doesNotMatch(matchingPool, /QueueDotCluster/)
  assert.doesNotMatch(matchingPool, /function getQueueDotTone/)
  assert.doesNotMatch(matchingPool, /maleWidth|femaleWidth|mixedWidth/)
  assert.doesNotMatch(matchingPool, /className="absolute h-2\.5 w-2\.5 rounded-full border border-white bg-boot-primary/)
  assert.doesNotMatch(matchingPool, /bg-rose-200|bg-amber-200|bg-sky-200/)
})

test('match hub defaults to group mode before exposing the solo flow', () => {
  const matchPage = readSource('app/match/page.tsx')

  assert.match(matchPage, /type MatchMode = 'group' \| 'solo'/)
  assert.match(matchPage, /useState<MatchMode>\('group'\)/)
  assert.match(matchPage, /function MatchModeSelector/)
  assert.match(matchPage, /과팅하기/)
  assert.match(matchPage, /소개팅하기/)
  assert.match(matchPage, /aria-pressed=\{mode === 'group'\}/)
  assert.match(matchPage, /aria-pressed=\{mode === 'solo'\}/)
  assert.match(matchPage, /setMatchMode\('group'\)/)
  assert.match(matchPage, /setMatchMode\('solo'\)/)
  assert.match(matchPage, /mode === 'group' \? \(/)
  assert.match(matchPage, /<GroupMatchStartPanel/)
  assert.match(matchPage, /<SoloMatchStartPanel/)
  assert.doesNotMatch(matchPage, /혼자 바로 매칭받기/)
})

test('solo matching is blocked while a group flow is active', () => {
  const matchPage = readSource('app/match/page.tsx')
  const matchStartPage = readSource('app/match/start/page.tsx')

  assert.match(matchPage, /const groupFlowActive =/)
  assert.match(matchPage, /const soloBlockedByGroupFlow = groupFlowActive/)
  assert.match(matchPage, /const effectiveMatchMode: MatchMode = soloBlockedByGroupFlow \? 'group' : matchMode/)
  assert.match(matchPage, /const isSoloMode = effectiveMatchMode === 'solo'/)
  assert.match(matchPage, /disabled=\{soloBlockedByGroupFlow\}/)
  assert.match(matchPage, /과팅 진행 중에는 소개팅을 잠시 막아둘게요/)
  assert.match(matchPage, /<MatchingPool[\s\S]+soloDisabled=\{soloBlockedByGroupFlow\}[\s\S]+groupQueueActive=\{isGroupQueueActive\}/)

  assert.match(matchStartPage, /function getDevPreviewGroupStatusFromServer/)
  assert.match(matchStartPage, /const soloBlockedByGroupFlow = mode === 'solo'/)
  assert.match(matchStartPage, /SoloBlockedByGroupFlowView/)
  assert.match(matchStartPage, /진행 중인 과팅을 먼저 마무리해 주세요/)
})

test('active group queue state replaces start buttons with cancelable waiting UI', () => {
  const matchPage = readSource('app/match/page.tsx')
  const matchingPool = readSource('components/MatchingPool.tsx')
  const darkTeamCard = readSource('components/matching/DarkTeamProgressCard.tsx')
  const queueRadar = readSource('components/matching/QueueRadarCard.tsx')

  assert.match(matchPage, /setDevPreviewGroupStatus/)
  assert.match(matchPage, /const isGroupQueueActive =/)
  assert.match(matchPage, /const handleCancelGroupQueue =/)
  assert.match(matchPage, /const handleCancelMatchResult =/)
  assert.match(matchPage, /function confirmAction/)
  assert.match(matchPage, /fetch\('\/api\/match-pool\/cancel'/)
  assert.match(matchPage, /\/api\/matches\/\$\{encodeURIComponent\(match\.match_id\)\}\/cancel/)
  assert.match(matchPage, /setDevPreviewGroupStatus\('ready'\)/)
  assert.match(matchPage, /NEXT AFTER MATCH/)
  assert.match(matchPage, /가매칭이 잡히면 데일리카드까지 이어져요/)
  assert.match(matchPage, /<ActiveGroupQueuePanel[\s\S]+canceling=\{cancelingQueue\}/)
  assert.match(matchPage, /<ActiveGroupQueuePanel[\s\S]+onCancel=\{handleCancelGroupQueue\}/)
  assert.match(matchPage, /function QueueControlStrip/)
  assert.match(matchPage, /canCancelCurrentMatch/)
  assert.match(matchPage, /handleCancelMatchResult\(currentMatchResult\)/)
  assert.match(matchPage, /cancelAction=\{canCancelCurrentMatch \? \{/)
  assert.match(matchPage, /가매칭 취소하기/)
  assert.match(matchPage, /과팅 매칭 취소하기/)
  assert.match(matchPage, /매칭 취소하기/)
  assert.match(matchPage, /큐 진입 완료 · 상대팀 탐색 중/)
  assert.match(matchPage, /showOpenSlot=\{!loading && !isGroupQueueActive/)
  assert.match(matchPage, /groupQueueActive=\{isGroupQueueActive\}/)

  const groupCreatePage = readSource('app/group/create/page.tsx')
  assert.match(groupCreatePage, /async function cancelQueue\(\)/)
  assert.match(groupCreatePage, /setDevPreviewGroupStatus\('ready'\)/)
  assert.doesNotMatch(groupCreatePage, /setDevPreviewGroupStatus\('forming'\)[\s\S]{0,160}status: 'forming'/)

  assert.match(matchingPool, /groupQueueActive/)
  assert.match(matchingPool, /hideStartAction/)
  assert.match(matchingPool, /현재 들어간 큐/)
  assert.match(matchingPool, /return hideStartAction \? \(/)
  assert.match(matchingPool, /href=\{`\/group\/create\?size=\$\{row\.size\}`\}/)

  assert.match(darkTeamCard, /showOpenSlot/)
  assert.match(darkTeamCard, /members\.length < 3 && showOpenSlot/)
  assert.match(queueRadar, /매칭 취소하기/)
  assert.doesNotMatch(queueRadar, /큐에서 빠지기/)
})

test('solo introduction flow is separate from group creation', () => {
  const matchPage = readSource('app/match/page.tsx')
  const matchStartPage = readSource('app/match/start/page.tsx')

  assert.match(matchPage, /mode'\) === 'solo'/)
  assert.match(matchPage, /soloStatus'\) === 'in_pool'/)
  assert.match(matchPage, /DEV_SOLO_MATCHES/)
  assert.match(matchPage, /<SoloMatchStartPanel/)
  assert.doesNotMatch(matchPage, />\s*Group Match\s*</)
  assert.match(matchPage, /<MatchSearchingPrivacyCard[\s\S]+mode=\{effectiveMatchMode\}/)
  assert.match(matchPage, /function QueueControlStrip/)
  assert.match(matchPage, /매칭 취소하기/)
  assert.match(matchPage, /소개팅 상대 후보/)
  assert.match(matchPage, /1:1 소개팅 상대가 도착했어요/)
  assert.match(matchPage, /지금은 \{targetLabel\}를 찾는 중이에요/)

  assert.match(matchStartPage, /type MatchStartMode = 'group' \| 'solo'/)
  assert.match(matchStartPage, /SOLO_REDIRECT_TO = '\/match\/start\?mode=solo'/)
  assert.match(matchStartPage, /1:1 소개팅 준비 완료/)
  assert.match(matchStartPage, /href="\/match\?mode=solo&soloStatus=in_pool"/)
  assert.match(matchStartPage, /href="\/match\?mode=solo&sampleMatches=1"/)
  assert.match(matchStartPage, /if \(steps\.every\(\(step\) => step\.done\) && mode === 'group'\) redirect\('\/group\/create'\)/)
})

test('solo queue and mock detail stay in the 1:1 flow', () => {
  const matchPage = readSource('app/match/page.tsx')
  const matchDetailPage = readSource('app/match/[id]/page.tsx')
  const matchingPool = readSource('components/MatchingPool.tsx')
  const notificationsPage = readSource('app/notifications/page.tsx')

  assert.match(matchPage, /explicitSoloPreview/)
  assert.match(matchPage, /setSoloQueueActive\(requestedMode === 'solo' && params\.get\('soloStatus'\) === 'in_pool'\)/)
  assert.match(matchPage, /setMatches\(params\.get\('sampleMatches'\) === '1' \? DEV_SOLO_MATCHES : \[\]\)/)
  assert.match(matchPage, /soloFlowActive/)
  assert.match(matchPage, /const handleCancelSoloQueue =/)
  assert.match(matchPage, /confirmAction\('1:1 매칭 찾기를 취소할까요/)
  assert.match(matchPage, /setDevPreviewSoloStatus\('idle'\)/)
  assert.match(matchPage, /1:1 매칭 취소하기/)
  assert.match(matchPage, /soloQueueActive=\{soloFlowActive\}/)
  assert.match(matchPage, /onCancelSoloQueue=\{handleCancelSoloQueue\}/)
  assert.match(matchPage, /soloResultHref/)
  assert.match(matchPage, /visibleMatches\.find\(\(match\) => match\.match_mode === 'solo'\)/)
  assert.match(matchPage, /PostMatchFlowCard/)
  assert.match(matchPage, /const shouldShowMatchingPool = !loading && !hasAnyStartedMatching && !hasMatchResults/)
  assert.match(matchPage, /visibleMatches\.length === 0 && hasStartedMatching && !isGroupQueueActive && !soloFlowActive/)
  assert.doesNotMatch(matchPage, /requestedMode === 'solo' && groupData\.group\?\.status === 'in_pool'[\s\S]+setMatchMode\('group'\)/)
  assert.match(matchPage, /매칭 큐에서 1:1 상대를 찾는 중이에요/)
  assert.match(matchPage, /이미 소개팅 찾기를 시작했어요/)
  assert.match(matchPage, /확정 후 오늘의 카드/)
  assert.match(matchPage, /확정 후 데일리카드와 약속 정보가 열립니다/)
  assert.match(matchPage, /function DailyCardFlowPreview/)
  assert.match(matchPage, /가매칭이 도착하면 열리는 것/)
  assert.match(matchPage, /\{targetLabel\}가 잡히면 사전 카드와 보증금 단계로 넘어가고/)
  assert.match(matchPage, /오늘 한 장을 직접 열어요/)
  assert.match(matchPage, /내가 써야 상대 힌트가 열려요/)

  const homeTaskCard = readSource('components/matching/HomeTodayTaskCard.tsx')
  assert.match(homeTaskCard, /if \(groupStatus === 'in_pool'\)/)
  assert.match(homeTaskCard, /if \(groupStatus === 'ready'\)/)
  assert.match(homeTaskCard, /이번 주 매칭을 시작할 수 있어요/)
  assert.match(homeTaskCard, /큐 진입 가능/)

  assert.match(matchingPool, /soloQueueActive/)
  assert.match(matchingPool, /onCancelSoloQueue/)
  assert.match(matchingPool, /soloResultHref/)
  assert.match(matchingPool, /매칭 취소하기/)
  assert.match(matchingPool, /1:1 가매칭이 도착했어요/)
  assert.match(matchingPool, /1:1 상대를 찾는 중이에요/)
  assert.match(matchingPool, /가매칭 준비 이어가기/)
  assert.match(matchingPool, /시작은 끝났고, 이제 기다리는 단계예요/)
  assert.match(matchingPool, /resultHref \?\? '\/notifications'/)

  assert.match(matchDetailPage, /matchId\.startsWith\('dev-solo-'\)/)
  assert.match(matchDetailPage, /match_mode: isSolo \? 'solo' : 'group'/)
  assert.match(matchDetailPage, /opp_group_size: participantCount/)
  assert.match(matchDetailPage, /createDevConnections\(matchId\)/)
  assert.match(matchDetailPage, /createDevAttendance\(matchId\)/)
  assert.match(matchDetailPage, /getOpponentSummary\(match: MatchDetail\)/)
  assert.match(matchDetailPage, /1:1 가매칭이 도착했어요!/)
  assert.match(matchDetailPage, /lockedTitle=\{currentMatch\.match_mode === 'solo' \? '상대 이름은 아직 비공개예요'/)
  assert.match(matchDetailPage, /getPendingStepCopy/)
  assert.match(matchDetailPage, /가매칭 취소하기/)
  assert.match(matchDetailPage, /지금은 내 준비 상태만 확인해요/)
  assert.match(matchDetailPage, /title: '나를 소개해요'/)
  assert.match(matchDetailPage, /첫 만남 전에 내 분위기를 짧게 적어볼게요/)
  assert.match(matchDetailPage, /내 소개 카드 작성/)
  assert.match(matchDetailPage, /mode=\{currentMatch\.match_mode === 'solo' \? 'solo' : 'group'\}/)
  assert.match(matchDetailPage, /function PendingUnlockPreview/)
  assert.match(matchDetailPage, /확정 후 열리는 것/)
  assert.match(matchDetailPage, /16-20시에 하루 한 장씩 직접 열고/)
  assert.match(matchDetailPage, /function TodayCardSummary/)
  assert.match(matchDetailPage, /TODAY CARD/)
  assert.match(matchDetailPage, /오늘의 공개 카드를 열어요/)
  assert.match(matchDetailPage, /아래 카드 목록에서 오늘 뽑기 버튼/)
  assert.match(matchDetailPage, /채팅\/연락처/)
  assert.match(matchDetailPage, /상대의 작은 힌트/)
  assert.match(matchDetailPage, /상대 연락처/)

  assert.match(notificationsPage, /daily_card_available/)
  assert.match(notificationsPage, /오늘의 데일리카드를 열어보세요!/)
  assert.match(notificationsPage, /dev-solo-match-pending/)
  assert.match(notificationsPage, /match_mode: 'solo'/)
  assert.match(notificationsPage, /isSoloMatchNotification/)
  assert.match(notificationsPage, /opp_group_size === 1/)
  assert.match(notificationsPage, /1:1 가매칭이 도착했어요!/)
  assert.match(notificationsPage, /상세는 확정 후 공개/)
  assert.doesNotMatch(notificationsPage, /심리학과|경영학과/)
})

test('home info modal explains the whole app flow with visual cards', () => {
  const homeInfo = readSource('components/matching/HomeInfoButton.tsx')

  assert.match(homeInfo, /앱 흐름 한눈에/)
  assert.match(homeInfo, /function FlowVisualCard/)
  assert.match(homeInfo, /UserPlus/)
  assert.match(homeInfo, /Sparkles/)
  assert.match(homeInfo, /CreditCard/)
  assert.match(homeInfo, /MessageCircle/)
})

test('daily card availability can generate in-app notifications', () => {
  const notificationApi = readSource('app/api/notifications/route.ts')
  const migration = readSource('supabase/migrations/20260701000000_daily_card_available_notifications.sql')

  assert.match(notificationApi, /notify_available_daily_cards/)
  assert.match(notificationApi, /get_my_notifications/)
  assert.match(migration, /daily_card_available/)
  assert.match(migration, /CREATE OR REPLACE FUNCTION public\.notify_available_daily_cards/)
  assert.match(migration, /SET search_path = ''/)
  assert.match(migration, /match_daily_card_schedule/)
  assert.match(migration, /INSERT INTO public\.notifications/)
  assert.match(migration, /FROM public\.notifications n/)
  assert.match(migration, /selected_at IS NULL/)
  assert.match(migration, /forfeited_at IS NULL/)
  assert.match(migration, /v_user_id UUID := auth\.uid\(\)/)
  assert.match(migration, /gm\.user_id = v_user_id/)
  assert.match(
    migration,
    /REVOKE ALL ON FUNCTION public\.notify_available_daily_cards\(UUID\) FROM PUBLIC/,
  )
  assert.match(migration, /NOT EXISTS/)
})

test('preference page makes age range selection visually prominent', () => {
  const preferencesPage = readSource('app/profile/preferences/page.tsx')

  assert.match(preferencesPage, /상대 나이 범위/)
  assert.match(preferencesPage, /Age range/)
  assert.match(preferencesPage, /function AgeControlCard/)
  assert.match(preferencesPage, /선호 범위/)
  assert.match(preferencesPage, /내 나이 ±3살로 다시 맞추기/)
})
