'use client'
import {useState} from 'react'
import Image from 'next/image'
import {ArrowRight} from 'lucide-react'
import {MentoringRolePicker} from '@/components/meetups/HostedMentoringLobby'
import {HostedRoomCard} from '@/components/meetups/HostedRoomCards'
import MeetupApplicationFlow from '@/components/meetups/MeetupApplicationFlow'
import {ApplicationReviewCards,RoomApplicationNotices} from '@/components/meetups/MeetupApplications'
import {ApplicationStatusCard} from '@/components/meetups/MeetupAdmissionStatus'
import type {ApplicationManagementView,ApplicantView,NativeApplicationKind} from '@/lib/meetups/application-view'
import {applicationChatPath} from '@/lib/meetups/application-view'
import type {AdmissionDepositQuote} from '@/lib/meetups/admission-contract'
import {NEW_ADMISSION_DEPOSIT_KRW} from '@/lib/meetups/admission-deposit-policy'
import s from '@/components/meetups/hosted-rooms.module.css'
import a from '@/components/meetups/meetup-admission.module.css'

/** Development+offline route only. No API interception, auth bypass, or real mutations. */
export default function HostedParticipationRehearsal(){
 const [kind,setKind]=useState<NativeApplicationKind>('mentoring'),[stage,setStage]=useState('rooms'),[role,setRole]=useState<'mentor'|'mentee'>('mentee')
 const [confirmation,setConfirmation]=useState<{application:ApplicantView;action:'approve'|'decline'}|null>(null)
 const [intro,setIntro]=useState('수업에서 막힌 부분을 같이 풀고 싶어요.'),[strength,setStrength]=useState('매번 이야기한 내용을 한 장으로 정리할게요.')
 const [accepted,setAccepted]=useState(false)
 const id='97000000-0000-4000-8000-000000000020',applicationId='97000000-0000-4000-8000-000000000021'
 const title=kind==='study'?'공학미적분, 한 챕터씩 같이':'전공 선택, 선배에게 물어봐'
 const quote:AdmissionDepositQuote={id:'97000000-0000-4000-8000-000000000022',room:{kind,id},amountKrw:10000,currency:'KRW',policyVersion:'rehearsal-only',expiresAt:'2099-01-01T00:00:00Z',paymentMethods:['new']}
 const data:ApplicationManagementView={accountKey:'97000000-0000-4000-8000-000000000023',room:{id,title,memberCount:accepted?4:3,capacity:kind==='study'?5:4},isHost:true,pendingCount:accepted?0:1,applications:[{id:applicationId,alias:'차분한 아틀라스',intro,strength,admission:accepted?'accepted':'pending',payment:'held',revision:1,createdAt:'2026-09-12T03:00:00Z',metadata:kind==='study'?{}:{role}}],notices:[{id:'97000000-0000-4000-8000-000000000024',kind:'application_received',text:'함께하고 싶은 새 참가 신청이 도착했어요. 방장이 확인하고 있어요.',createdAt:'2026-09-12T03:00:00Z'}],hasMore:false,nextCursor:null}
 const stages=[['rooms','모집방'],['application','보증금·신청'],['host','방장 검토'],['accepted','승인 후'],['chat','기존 대화']] as const
 return <><div className={`${s.page} ${stage==='application'?'!pb-0':''}`}><aside className={s.demo}><b>스터디·멘토링 흐름 리허설</b><br/>신규 보증금 기준은 10,000원이에요. 이 화면의 참여자·결제·신청 결과는 가상 예시이며 실제 결제·신청·알림은 발생하지 않아요.</aside><nav className={s.tabs} aria-label="모집 종류">{(['mentoring','study'] as const).map(k=><button className={kind===k?s.button:s.secondary} key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setStage('rooms');setAccepted(false);setConfirmation(null)}}>{k==='study'?'전공 스터디':'멘토링'}</button>)}</nav><nav className={s.tabs} aria-label="모집 흐름 단계">{stages.map(([key,label])=><button className={stage===key?s.quiet:s.secondary} key={key} aria-pressed={stage===key} onClick={()=>setStage(key)}>{label}</button>)}</nav>
 {stage==='rooms'?<><header className={s.header}><span className={s.eyebrow}>OUR DEPARTMENT, TOGETHER</span><h1>{kind==='study'?'혼자 막히던 부분도, 같이.':'질문 하나, 경험 하나.'}</h1><p>{kind==='study'?'내 과목의 열린 방에 신청하거나, 이름을 정해 새 모임을 열어요.':'마음에 맞는 모임을 고르고 내 역할로 신청해요.'}</p></header>{kind==='mentoring'?<MentoringRolePicker onChoose={r=>{setRole(r);setStage('application')}}/>:<Image src="/social-scenes/course-calculus.png" alt="수식과 풀이 노트 · 과목 활동 예시" width={780} height={400} className={s.hero}/>}<div className={s.bar}><h2>함께할 모임</h2><p>가상 모집방 예시</p></div><HostedRoomCard room={{id,title,label:kind==='study'?'미래에너지공학과 · 1/10회차':'미래에너지공학과 · 수업·전공 이야기',count:3,capacity:kind==='study'?5:4,joined:false,isHost:false,closed:false,href:'#rehearsal-apply',...(kind==='mentoring'?{roles:{mentor:2,mentee:1,size:2}}:{})}}/><button id="rehearsal-apply" className={`${s.button} mt-4 w-full`} onClick={()=>setStage('application')}>이 방 참가 신청 살펴보기<ArrowRight size={16}/></button></>:null}
 {stage==='host'?<><aside className={s.details}><b>방장 개인 알림 예시</b><p>새 참가 신청이 왔어요 · {title}</p><p>방 알림과 별개로 알림함·퀀텀 안내에서 확인해요.</p></aside><section className={`${a.surface} mt-4`}><div className={a.heading}><div><span className={a.eyebrow}>TOGETHER, NEXT</span><h2>함께하고 싶은 사람들이에요</h2></div><span className={a.badge}>대기 {data.pendingCount}명</span></div><p className={a.intro}>{title} · {data.room.memberCount}/{data.room.capacity}명<br/>소개·장점은 방장에게만 보여요.</p><ApplicationReviewCards data={data} confirmation={confirmation} onChoose={(application,action)=>setConfirmation({application,action})} onBack={()=>setConfirmation(null)} onConfirm={()=>{if(confirmation?.action==='approve'){setAccepted(true);setStage('accepted')}else setStage('rooms');setConfirmation(null)}}/></section></>:null}
 {stage==='accepted'?<ApplicationStatusCard application={{id:applicationId,admission:'accepted',payment:'held',amountKrw:10000,revision:2,chatHref:applicationChatPath(id,kind)}} onRefresh={()=>{}} onCancel={()=>{}} onBack={()=>{}} onConfirm={()=>{}} onOpenChat={()=>setStage('chat')}/>:null}
 {stage==='chat'?<><header className={s.detailHeader}><span className={s.eyebrow}>채팅 / {kind==='study'?'전공 스터디':'선후배 멘토링'}</span><h2>{title}</h2><p className={s.note}>이전 대화 · 가상 예시</p></header><div className={s.chat}><article className={s.message}><small>초록빛 오로라</small><p>목요일 6시, 도서관 앞에서 만날까요? 첫날은 질문 하나씩 준비해 와요.</p></article><RoomApplicationNotices data={{...data,isHost:false,pendingCount:0}} kind={kind}/><article className={s.message}><small>따뜻한 페가수스</small><p>좋아요! 늦게 들어오신 분도 위 약속을 확인해 주세요.</p></article></div><p className={s.details}>실제 앱에서는 수락된 사람이 채팅 탭의 이 방으로 들어와 이전 대화를 읽어요. 이 화면은 대화 구조를 보여주는 예시예요.</p></>:null}
 </div>{stage==='application'?<MeetupApplicationFlow key={`${kind}:${role}`} room={{kind,id}} accountKey="offline-rehearsal" quote={quote} newDepositAmountKrw={NEW_ADMISSION_DEPOSIT_KRW} policy={{summary:'흐름 확인용 가상 정책이에요. 실제 운영 정책이 아닙니다.',conditions:['방장 수락 전 취소·미승인은 반환 대상으로 처리해요.','반환 대상과 실제 반환 완료는 별개예요.','신고만으로 자동 몰수하지 않아요.']}} meetup={{title,activityLabel:kind==='study'?'우리 과 전공 스터디':role==='mentor'?'멘토링 · 경험 나눔':'멘토링 · 도움 구함',imageSrc:kind==='study'?'/social-scenes/course-calculus.png':'/images/quantum-campus-group.webp',summary:`3/${kind==='study'?5:4}명 · 신청 확인 후 채팅 입장`,scheduleLabel:'날짜는 채팅에서 함께 정해요',locationLabel:'장소는 채팅에서 함께 정해요'}} onCancel={()=>setStage('rooms')} onSubmit={async input=>{setIntro(input.intro);setStrength(input.strength??'');return {applicationId,admission:'submitted',payment:'held'}}}/>:null}{stage==='application'?<div className="mx-auto max-w-xl px-5 pb-28"><button className={`${s.secondary} w-full`} onClick={()=>setStage('host')}>방장에게 어떻게 보이는지 보기<ArrowRight size={16}/></button></div>:null}</>
}
