'use client'
import {useRef,useState,type MouseEvent} from 'react'
import Image from 'next/image'
import Link from 'next/link'
import {ArrowRight,Bell,Check,UsersRound} from 'lucide-react'
import {NotificationContext,type NotificationState} from '@/components/notifications/NotificationsProvider'
import {NotificationArrival,NotificationsScreen,QuantumGuideEntry} from '@/components/notifications/NotificationSurfaces'
import NotificationBell from '@/components/NotificationBell'
import AppBottomNav from '@/components/navigation/AppBottomNav'
import {notificationPresentation} from '@/lib/notifications/common-presentation'
import type {NotificationRow} from '@/lib/notifications/common-contract'
import s from './notification-rehearsal.module.css'
type Scene='home'|'inbox'|'chat'|'guide'|'team'
const make=(event:string,n:number,domain='league'):NotificationRow=>({id:'65000000-0000-4000-8000-'+String(n).padStart(12,'0'),kind:'social_activity',read_at:null,created_at:new Date().toISOString(),payload:{version:1,domain,event,context_label:domain==='league'?'석탄 에너지 · LoL':'오늘 저녁, 같이 한 끼',entity_id:'66000000-0000-4000-8000-000000000001',audience:'organizer',body:event==='application_received'?'서포터 자리에 새 신청이 왔어요. 포부와 장점을 보고 함께할 멤버를 골라주세요.':event==='member_joined'?'모임에 새 멤버가 들어왔어요. 대화방에서 인사를 나눠보세요.':event==='application_accepted'?'이제 팀원이에요. 우리 팀에서 함께 경기를 준비해요.':'모두 모였어요. 우리 팀과 겨룰 상대를 살펴보세요.',status:'current'}})
export default function NotificationRehearsal(){
 const [scene,setScene]=useState<Scene>('home'),[role,setRole]=useState<'captain'|'applicant'>('captain'),[captain,setCaptain]=useState<NotificationRow[]>([]),[applicant,setApplicant]=useState<NotificationRow[]>([]),[arrival,setArrival]=useState<NotificationRow|null>(null),[pending,setPending]=useState(false),[full,setFull]=useState(false),[notice,setNotice]=useState('')
 const rows=role==='captain'?captain:applicant,write=role==='captain'?setCaptain:setApplicant
 const sequence=useRef(10),pendingId=useRef<string|null>(null)
 const unread=rows.filter(n=>!n.read_at).length
 const markRead=async(id?:string)=>{write(old=>old.map(n=>!id||n.id===id?{...n,read_at:n.read_at??new Date().toISOString()}:n));setArrival(null);return true}
 const context:NotificationState={items:rows,unread,status:'ready',hasMore:false,busy:false,arrival,error:null,refresh:async()=>{},loadMore:async()=>{},markRead,dismissArrival:()=>setArrival(null)}
 function addApplication(){if(pending||full)return;const row=make('application_received',++sequence.current);pendingId.current=row.id;setCaptain(old=>[row,...old]);setPending(true);if(role==='captain')setArrival(row)}
 function approve(){setPending(false);pendingId.current=null;setFull(true);setCaptain(old=>[make('room_ready',++sequence.current),...old]);setApplicant(old=>[make('application_accepted',++sequence.current),...old]);setNotice('수락 결과가 신청자의 알림함과 퀀텀 안내에 전달됐어요.')}
 function decline(){setPending(false);pendingId.current=null;const row=make('application_declined',++sequence.current);row.payload.body='이번 팀에는 함께하지 못했어요. 다른 팀의 빈자리를 확인해 볼 수 있어요.';setApplicant(old=>[row,...old]);setNotice('신청자에게 결과를 전달했어요. 서포터 자리는 계속 모집 중이에요.')}
 function open(row:NotificationRow){void markRead(row.id);if(row.payload.domain!=='league'){setNotice('일반 모임 소식이 도착했어요. 실제 서비스에서는 해당 모임으로 연결되며, 이 리허설은 알림 수신까지만 재현합니다.');return}if(row.payload.event==='application_received'&&(!pending||row.id!==pendingId.current)){setNotice('이미 처리된 신청이에요. 다시 승인하지 않아요.');return}setScene('team')}
 function navigate(e:MouseEvent<HTMLDivElement>){const link=(e.target as Element).closest('a');if(!link)return;const href=link.getAttribute('href');const targets:Record<string,Scene>={'/':'home','/match':'home','/meetups':'home','/community':'home','/profile/edit':'home','/chat':'chat','/chat/quantum':'guide','/notifications':'inbox'};if(href&&targets[href]){e.preventDefault();setScene(targets[href]);setArrival(null)}}
 return <NotificationContext.Provider value={context}><div onClickCapture={navigate}>
  <aside className={s.demoBar}><strong>로컬 알림 리허설 · 가상 계정</strong><p>실제 알림함·안내 카드 컴포넌트를 사용합니다. 실제 계정 발송이 아닙니다.</p><div><button aria-pressed={role==='captain'} onClick={()=>{setRole('captain');setScene('home');setArrival(null);setNotice('')}}>주장 화면</button><button aria-pressed={role==='applicant'} onClick={()=>{setRole('applicant');setScene('chat');setArrival(null);setNotice('')}}>신청자 화면</button><button onClick={addApplication} disabled={pending||full}>새 신청 도착</button><button onClick={()=>{const row=make('member_joined',5,'meetup');setCaptain(old=>[row,...old.filter(n=>n.id!==row.id)]);if(role==='captain')setArrival(row)}}>일반 모임 참가</button><button onClick={()=>{setCaptain([]);setApplicant([]);setPending(false);setFull(false);setNotice('');setScene('home');setArrival(null)}}>처음부터</button></div></aside>
  <nav className={s.sceneTabs} aria-label="리허설 화면">{([['home','다른 화면'],['inbox','알림함'],['chat','채팅'],['guide','퀀텀 안내'],['team','내 팀']] as [Scene,string][]).map(([value,label])=><button key={value} aria-pressed={scene===value} onClick={()=>setScene(value)}>{label}</button>)}</nav>
  {notice?<p className={s.notice} role="status">{notice}</p>:null}
  {scene==='inbox'||scene==='guide'?<NotificationsScreen embedded message={scene==='guide'} onOpen={open}/>:scene==='chat'?<main className={s.scene}><header><div><small>QUANTUM CHAT</small><h1>채팅</h1></div><NotificationBell/></header><QuantumGuideEntry/><section className={s.empty}><UsersRound size={26}/><h2>친구와의 대화는 그대로</h2><p>신청·초대 소식은 위의 퀀텀 안내에 도착해요.</p></section></main>:scene==='team'?<main className={s.scene}><header><div><small>우리 학교 리그 · LoL</small><h1>석탄 에너지</h1></div><NotificationBell/></header><div className={s.status}><span>확정 <b>{full?'5':'4'}/5</b></span><span>검토할 신청 <b>{pending?1:0}</b></span><span>초대 응답 대기 <b>0</b></span></div>{pending&&role==='captain'?<section className={s.application}><small>서포터 자리 · 참가 신청</small><h2>오늘의 닉네임 · 에메랄드</h2><Image src="/game-assets/lol-ranks/emerald.png" alt="" width={56} height={56}/><p>“팀 분위기는 제가 맡을게요. 시야 관리 자신 있어요!”</p><div><button onClick={approve}><Check size={16}/>같이하기</button><button onClick={decline}>이번에는 거절</button></div></section>:<section className={s.empty}><h2>{full?'우리 팀이 모두 모였어요':role==='applicant'?'참가 신청 결과를 기다리고 있어요':'서포터 한 자리, 함께할 친구를 기다려요'}</h2><p>{full?'다음 단계는 상대 팀 선택이에요. 실제 리그 화면에서 상대를 보고 대전을 제안합니다.':'화면을 나와도 새 소식은 알림함과 퀀텀 안내에 남아요.'}</p></section>}<Link className={s.realLink} href="/meetups/dev-flow?scene=league&flow=recruitment&sport=lol">실제 지도·신청 검토 UI 열기 <ArrowRight size={17}/></Link><p className={s.fine}>이 요약 화면은 두 가상 계정의 알림 전이를 보여줍니다. 지도 검토는 위 링크의 실제 리그 컴포넌트에서 확인합니다.</p></main>:<main className={s.scene}><header><div><small>QUANTUM CAMPUS</small><h1>오늘, 같이 놀 사람!</h1></div><NotificationBell/></header><p className={s.intro}>모집 화면을 나와, 다른 콘텐츠를 보는 중이에요.</p><div className={s.photo}><Image src="/images/meetups/meetup-cafe-friends-v1.webp" alt="카페에서 함께 이야기하는 활동 분위기" fill sizes="(max-width:640px) 100vw,640px"/><span>잠깐의 여유, 새로운 친구와.</span></div><button className={s.myTeam} onClick={()=>setScene('team')}><span><small>내가 모집 중인 팀</small><strong>석탄 에너지 · {full?'5':'4'}/5</strong></span><span>{pending?'신청 1건 검토':'내 팀 보기'} <ArrowRight size={17}/></span></button><QuantumGuideEntry/></main>}
  <AppBottomNav previewPathname={scene==='chat'||scene==='guide'?'/chat':scene==='team'?'/meetups':'/'}/>
  <NotificationArrival/>
 </div></NotificationContext.Provider>
}
